// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: remote_read.proto
#ifndef GRPC_remote_5fread_2eproto__INCLUDED
#define GRPC_remote_5fread_2eproto__INCLUDED

#include "remote_read.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace gauss {

class RemoteRead final {
 public:
  static constexpr char const* service_full_name() {
    return "gauss.RemoteRead";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetCU(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::gauss::CUResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gauss::CUResponse>> AsyncGetCU(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gauss::CUResponse>>(AsyncGetCURaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gauss::CUResponse>> PrepareAsyncGetCU(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gauss::CUResponse>>(PrepareAsyncGetCURaw(context, request, cq));
    }
    virtual ::grpc::Status GetPage(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::gauss::PageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gauss::PageResponse>> AsyncGetPage(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gauss::PageResponse>>(AsyncGetPageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gauss::PageResponse>> PrepareAsyncGetPage(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gauss::PageResponse>>(PrepareAsyncGetPageRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetCU(::grpc::ClientContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCU(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gauss::CUResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCU(::grpc::ClientContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void GetCU(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gauss::CUResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void GetPage(::grpc::ClientContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gauss::PageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPage(::grpc::ClientContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void GetPage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gauss::PageResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gauss::CUResponse>* AsyncGetCURaw(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gauss::CUResponse>* PrepareAsyncGetCURaw(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gauss::PageResponse>* AsyncGetPageRaw(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gauss::PageResponse>* PrepareAsyncGetPageRaw(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetCU(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::gauss::CUResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gauss::CUResponse>> AsyncGetCU(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gauss::CUResponse>>(AsyncGetCURaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gauss::CUResponse>> PrepareAsyncGetCU(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gauss::CUResponse>>(PrepareAsyncGetCURaw(context, request, cq));
    }
    ::grpc::Status GetPage(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::gauss::PageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gauss::PageResponse>> AsyncGetPage(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gauss::PageResponse>>(AsyncGetPageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gauss::PageResponse>> PrepareAsyncGetPage(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gauss::PageResponse>>(PrepareAsyncGetPageRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetCU(::grpc::ClientContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response, std::function<void(::grpc::Status)>) override;
      void GetCU(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gauss::CUResponse* response, std::function<void(::grpc::Status)>) override;
      void GetCU(::grpc::ClientContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void GetCU(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gauss::CUResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void GetPage(::grpc::ClientContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response, std::function<void(::grpc::Status)>) override;
      void GetPage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gauss::PageResponse* response, std::function<void(::grpc::Status)>) override;
      void GetPage(::grpc::ClientContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void GetPage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gauss::PageResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::gauss::CUResponse>* AsyncGetCURaw(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gauss::CUResponse>* PrepareAsyncGetCURaw(::grpc::ClientContext* context, const ::gauss::CURequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gauss::PageResponse>* AsyncGetPageRaw(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gauss::PageResponse>* PrepareAsyncGetPageRaw(::grpc::ClientContext* context, const ::gauss::PageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetCU_;
    const ::grpc::internal::RpcMethod rpcmethod_GetPage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetCU(::grpc::ServerContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response);
    virtual ::grpc::Status GetPage(::grpc::ServerContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCU : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetCU() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetCU() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCU(::grpc::ServerContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCU(::grpc::ServerContext* context, ::gauss::CURequest* request, ::grpc::ServerAsyncResponseWriter< ::gauss::CUResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetPage() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPage(::grpc::ServerContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPage(::grpc::ServerContext* context, ::gauss::PageRequest* request, ::grpc::ServerAsyncResponseWriter< ::gauss::PageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetCU<WithAsyncMethod_GetPage<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetCU : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_GetCU() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::gauss::CURequest, ::gauss::CUResponse>(
          [this](::grpc::ServerContext* context,
                 const ::gauss::CURequest* request,
                 ::gauss::CUResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->GetCU(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_GetCU(
        ::grpc::experimental::MessageAllocator< ::gauss::CURequest, ::gauss::CUResponse>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gauss::CURequest, ::gauss::CUResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetCU() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCU(::grpc::ServerContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetCU(::grpc::ServerContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_GetPage() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::gauss::PageRequest, ::gauss::PageResponse>(
          [this](::grpc::ServerContext* context,
                 const ::gauss::PageRequest* request,
                 ::gauss::PageResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->GetPage(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_GetPage(
        ::grpc::experimental::MessageAllocator< ::gauss::PageRequest, ::gauss::PageResponse>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gauss::PageRequest, ::gauss::PageResponse>*>(
          ::grpc::Service::experimental().GetHandler(1))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPage(::grpc::ServerContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetPage(::grpc::ServerContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_GetCU<ExperimentalWithCallbackMethod_GetPage<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetCU : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetCU() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetCU() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCU(::grpc::ServerContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetPage() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPage(::grpc::ServerContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCU : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GetCU() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetCU() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCU(::grpc::ServerContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCU(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GetPage() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPage(::grpc::ServerContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetCU : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_GetCU() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->GetCU(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_GetCU() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCU(::grpc::ServerContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetCU(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_GetPage() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->GetPage(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_GetPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPage(::grpc::ServerContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetPage(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCU : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetCU() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::gauss::CURequest, ::gauss::CUResponse>(std::bind(&WithStreamedUnaryMethod_GetCU<BaseClass>::StreamedGetCU, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetCU() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCU(::grpc::ServerContext* context, const ::gauss::CURequest* request, ::gauss::CUResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCU(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gauss::CURequest,::gauss::CUResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetPage() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::gauss::PageRequest, ::gauss::PageResponse>(std::bind(&WithStreamedUnaryMethod_GetPage<BaseClass>::StreamedGetPage, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPage(::grpc::ServerContext* context, const ::gauss::PageRequest* request, ::gauss::PageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gauss::PageRequest,::gauss::PageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetCU<WithStreamedUnaryMethod_GetPage<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetCU<WithStreamedUnaryMethod_GetPage<Service > > StreamedService;
};

}  // namespace gauss


#endif  // GRPC_remote_5fread_2eproto__INCLUDED
