subdir = src/common/interfaces/libpq/jdbc
top_builddir = ../../../../../
backenddir = $(top_builddir)/src/common/backend
include $(top_builddir)/src/Makefile.global

SUBDIRS=client_logic_jni
clean:
	rm -f client_logic_jni/*.o
$(recurse)

