#
# Makefile for the common subsystem
#
# src/common/backend/Makefile
#

subdir = src/common/backend
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = catalog  client_logic  lib  libpq  nodes  parser  port  regex  snowball  tsearch  utils pgxc_single

include $(top_srcdir)/src/gausskernel/common.mk
