#
# Makefile for the pgxc remote query
#
# src/common/backend/pgxc/Makefile
#

subdir = src/common/backend/pgxc_single
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = barrier locator copy nodemgr pool

include $(top_srcdir)/src/gausskernel/common.mk
