thread_pool_attr='16,1,(nobind)'
enable_asp=off
enable_thread_pool=off
enable_ustore=off
asp_sample_num=10
enable_incremental_checkpoint=off
enable_double_write=off
enable_stmt_track=off
use_workload_manager=off
enable_instr_rt_percentile=off
enable_wdr_snapshot=off
enable_global_syscache=on

shared_buffers=64MB
wal_buffers=16MB
cstore_buffers=256kB
segment_buffers=16
bulk_read_ring_size=256kB
bulk_write_ring_size=256kB
num_internal_lock_partitions='CLOG_PART=1,CSNLOG_PART=1,LOG2_LOCKTABLE_PART=4,TWOPHASE_PART=1,FASTPATH_PART=20'
max_locks_per_transaction=64
max_prepared_transactions=0
audit_file_remain_threshold=1024
max_connections=200
track_activity_query_size=200
max_inner_tool_connections=10
global_syscache_threshold=128MB
local_syscache_threshold=4MB
wal_flush_timeout=800
wal_flush_delay=100
ustore_attr='ustore_verify_level=NONE;ustore_verify_module=NULL'
