/*
 * Copyright (c) 2020 Huawei Technologies Co.,Ltd.
 *
 * openGauss is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 * ---------------------------------------------------------------------------------------
 * 
 * memory_lite.h
 * 
 * 
 * 
 * IDENTIFICATION
 *        src/include/lite/memory_lite.h
 *
 * ---------------------------------------------------------------------------------------
 */


#ifndef MEMORY_LITE_H
#define MEMORY_LITE_H

#ifdef ENABLE_LITE_MODE
#define PARTITION_OID_INDEX_ID_NBUCKETS 512
#define PARTITION_PART_OID_INDEX_ID_NBUCKETS 512
#define PARTITION_INDEX_TABLE_ID_PARENT_OID_INDEX_ID_NBUCKETS 512
#define PG_JOB_ID_INDEX_ID_NBUCKETS 4
#define PG_OBJECT_INDEX_NBUCKETS 4
#define PGXC_CLASS_PGXC_REL_ID_INDEX_ID_NBUCKETS 4
#define PGXC_GROUP_GROUP_NAME_INDEX_ID_NBUCKETS 4
#define PGXC_GROUP_OID_INDEX_ID_NBUCKETS 4
#define PGXC_NODE_NODE_NAME_INDEX_ID_NBUCKETS 4
#define PGXC_NODE_OID_INDEX_ID_NBUCKETS 4
#define PGXC_NODE_NODE_ID_INDEX_ID_NBUCKETS 4
#define WORKLOAD_GROUP_GROUP_NAME_INDEX_ID_NBUCKETS 4
#define WORKLOAD_GROUP_OID_INDEX_ID_NBUCKETS 4
#define PGXC_SLICE_INDEX_ID_NBUCKETS 4
#define STATISTIC_RELID_KIND_ATTNUM_INH_INDEX_ID_NBUCKETS 4
#define STATISTIC_EXT_RELID_KIND_INH_KEY_INDEX_ID_NBUCKETS 4
#define PACKAGE_OID_INDEX_ID_NBUCKETS 4
#define PACKAGE_NAME_INDEX_ID_NBUCKETS 4
#define STREAMING_CONT_QUERY_DEFRELID_INDEX_ID_NBUCKETS 4
#define STREAMING_CONT_QUERY_ID_INDEX_ID_NBUCKETS 4
#define STREAMING_CONT_QUERY_LOOKUP_ID_XID_INDEX_ID_NBUCKETS 4
#define STREAMING_CONT_QUERY_MATRELID_INDEX_ID_NBUCKETS 4
#define STREAMING_CONT_QUERY_OID_INDEX_ID_NBUCKETS 4
#define STREAMING_CONT_QUERY_RELID_INDEX_ID_NBUCKETS 4
#define STREAMING_CONT_QUERY_SCHEMA_CHANGE_INDEX_ID_NBUCKETS 4
#define STREAMING_STREAM_OID_INDEX_ID_NBUCKETS 4
#define STREAMING_STREAM_RELID_INDEX_ID_NBUCKETS 4
#define STREAMING_REAPER_STATUS_OID_INDEX_ID_NBUCKETS 4
#define STREAMING_CQ_REAPER_STATUS_OID_INDEX_ID_NBUCKETS 4
#define ATTRIBUTE_REL_ID_NAME_INDEX_ID_NBUCKETS 512
#define ATTRIBUTE_REL_ID_NUM_INDEX_ID_NBUCKETS 512
#define CLIENT_LOGIC_CACHED_SEC_COL_OID_INDEX_ID_NBUCKETS 1
#define CLIENT_LOGIC_CACHED_SEC_COL_NAME_INDEX_ID_NBUCKETS 1
#define CLIENT_LOGIC_COL_SETTING_DISTRIBUTED_ID_INDEX_ID_NBUCKETS 1
#define CLIENT_LOGIC_COL_SETTING_NAME_INDEX_ID_NBUCKETS 1
#define CLIENT_LOGIC_COL_SETTING_OID_INDEX_ID_NBUCKETS 1
#define DATA_SOURCE_NAME_INDEX_ID_NBUCKETS 1
#define DATA_SOURCE_OID_INDEX_ID_NBUCKETS 1
#define MODEL_REL_ID_GSMODEL_OID_INDEX_ID_NBUCKETS 1
#define MODEL_REL_ID_GSMODEL_NAME_INDEX_ID_NBUCKETS 1
#define PG_DERECTORY_NAME_INDEX_ID_NBUCKETS 4
#define PG_DERECTORY_OID_INDEX_ID_NBUCKETS 4
#define FOREIGN_DATA_WRPPER_NAME_INDEX_ID_NBUCKETS 1
#define FOREIGN_DATA_WRPPER_OID_INDEX_ID_NBUCKETS 1
#define FOREIGN_SERVER_NAME_INDEX_ID_NBUCKETS 1
#define FOREIGN_SERVER_OID_INDEX_ID_NBUCKETS 1
#define FOREIGN_TABLE_REL_ID_INDEX_ID_NBUCKETS 1
#define CLIENT_LOGIC_GLOBAL_SETTING_NAME_INDEX_ID_NBUCKETS 1
#define CLIENT_LOGIC_GLOBAL_SETTING_OID_INDEX_ID_NBUCKETS 1
#define CLIENT_LOGIC_PROC_FUNC_ID_INDEX_ID_NBUCKETS 1
#define CLIENT_LOGIC_PROC_OID_INDEX_ID_NBUCKETS 1
#define GS_JOB_ARGUMENT_NAME_INDEX_ID_NBUCKETS 64
#define GS_JOB_ARGUMENT_POSITION_INDEX_ID_NBUCKETS 64
#define GS_JOB_ATTRIBUTE_NAME_INDEX_ID_NBUCKETS 64
#define GS_OPT_MODEL_NAME_INDEX_ID_NBUCKETS 64
#define RESOURCE_POOL_NAME_INDEX_ID_NBUCKETS 1
#define RESOURCE_POOL_OID_INDEX_ID_NBUCKETS 1
#define APP_WORKLOAD_GROUP_MAPPING_NAME_INDEX_ID_NBUCKETS 1
#define APP_WORKLOAD_GROUP_MAPPING_OID_INDEX_ID_NBUCKETS 1
#define SUBSCRIPTION_NAME_INDEX_ID_NBUCKETS 1
#define SUBSCRIPTION_OID_INDEX_ID_NBUCKETS 1
#define PUBLICATION_REL_MAP_INDEX_ID_NBUCKETS 1
#define SYNONYM_OID_INDEX_ID_NBUCKETS 1
#define SYNONYM_NAME_NSP_INDEX_ID_NBUCKETS 1
#define TS_CONFIG_MAP_INDEX_ID_NBUCKETS 1
#define TS_CONFIG_NAME_NSP_INDEX_ID_NBUCKETS 1
#define TS_CONFIG_OID_NSP_INDEX_ID_NBUCKETS 1
#define TS_DERECTORY_NAME_NSP_INDEX_ID_NBUCKETS 1
#define TS_DERECTORY_OID_INDEX_ID_NBUCKETS 1
#define TS_PARSE_NAME_NSP_INDEX_ID_NBUCKETS 1
#define TS_PARSE_OID_INDEX_ID_NBUCKETS 1
#define TS_TEMPLATE_NAME_NSP_INDEX_ID_NBUCKETS 1
#define TS_TEMPLATE_OID_INDEX_ID_NBUCKETS 1
#define PUBLICATION_NAME_INDEX_ID_NBUCKETS 1
#define PUBLICATION_OID_INDEX_ID_NBUCKETS 1
#define UID_REL_ID_INDEX_ID_NBUCKETS 1
#define DB_PRIVILEGE_OID_INDEX_ID_NBUCKETS 4
#define DB_PRIVILEGE_ROLE_ID_INDEX_ID_NBUCKETS 4
#define DB_PRIVILEGE_ROLE_ID_PRIVILEGE_TYPE_INDEX_ID_NBUCKETS 4
#else

#define PARTITION_OID_INDEX_ID_NBUCKETS 1024
#define PARTITION_PART_OID_INDEX_ID_NBUCKETS 1024
#define PARTITION_INDEX_TABLE_ID_PARENT_OID_INDEX_ID_NBUCKETS 1024
#define PG_JOB_ID_INDEX_ID_NBUCKETS 2048
#define PG_OBJECT_INDEX_NBUCKETS 2048
#define PGXC_CLASS_PGXC_REL_ID_INDEX_ID_NBUCKETS 1024
#define PGXC_GROUP_GROUP_NAME_INDEX_ID_NBUCKETS 256
#define PGXC_GROUP_OID_INDEX_ID_NBUCKETS 256
#define PGXC_NODE_NODE_NAME_INDEX_ID_NBUCKETS 256
#define PGXC_NODE_OID_INDEX_ID_NBUCKETS 256
#define PGXC_NODE_NODE_ID_INDEX_ID_NBUCKETS 256
#define WORKLOAD_GROUP_GROUP_NAME_INDEX_ID_NBUCKETS 256
#define WORKLOAD_GROUP_OID_INDEX_ID_NBUCKETS 256
#define PGXC_SLICE_INDEX_ID_NBUCKETS 1024
#define STATISTIC_RELID_KIND_ATTNUM_INH_INDEX_ID_NBUCKETS 1024
#define STATISTIC_EXT_RELID_KIND_INH_KEY_INDEX_ID_NBUCKETS 1024
#define PACKAGE_OID_INDEX_ID_NBUCKETS 2048
#define PACKAGE_NAME_INDEX_ID_NBUCKETS 2048
#define STREAMING_CONT_QUERY_DEFRELID_INDEX_ID_NBUCKETS 2048
#define STREAMING_CONT_QUERY_ID_INDEX_ID_NBUCKETS 2048
#define STREAMING_CONT_QUERY_LOOKUP_ID_XID_INDEX_ID_NBUCKETS 2048
#define STREAMING_CONT_QUERY_MATRELID_INDEX_ID_NBUCKETS 2048
#define STREAMING_CONT_QUERY_OID_INDEX_ID_NBUCKETS 2048
#define STREAMING_CONT_QUERY_RELID_INDEX_ID_NBUCKETS 2048
#define STREAMING_CONT_QUERY_SCHEMA_CHANGE_INDEX_ID_NBUCKETS 2048
#define STREAMING_STREAM_OID_INDEX_ID_NBUCKETS 2048
#define STREAMING_STREAM_RELID_INDEX_ID_NBUCKETS 2048
#define STREAMING_REAPER_STATUS_OID_INDEX_ID_NBUCKETS 2048
#define STREAMING_CQ_REAPER_STATUS_OID_INDEX_ID_NBUCKETS 2048
#define ATTRIBUTE_REL_ID_NAME_INDEX_ID_NBUCKETS 2048
#define ATTRIBUTE_REL_ID_NUM_INDEX_ID_NBUCKETS 2048
#define CLIENT_LOGIC_CACHED_SEC_COL_OID_INDEX_ID_NBUCKETS 128
#define CLIENT_LOGIC_CACHED_SEC_COL_NAME_INDEX_ID_NBUCKETS 128
#define CLIENT_LOGIC_COL_SETTING_DISTRIBUTED_ID_INDEX_ID_NBUCKETS 128
#define CLIENT_LOGIC_COL_SETTING_NAME_INDEX_ID_NBUCKETS 128
#define CLIENT_LOGIC_COL_SETTING_OID_INDEX_ID_NBUCKETS 128
#define DATA_SOURCE_NAME_INDEX_ID_NBUCKETS 32
#define DATA_SOURCE_OID_INDEX_ID_NBUCKETS 32
#define MODEL_REL_ID_GSMODEL_OID_INDEX_ID_NBUCKETS 256
#define MODEL_REL_ID_GSMODEL_NAME_INDEX_ID_NBUCKETS 256
#define PG_DERECTORY_NAME_INDEX_ID_NBUCKETS 64
#define PG_DERECTORY_OID_INDEX_ID_NBUCKETS 64
#define FOREIGN_DATA_WRPPER_NAME_INDEX_ID_NBUCKETS 8
#define FOREIGN_DATA_WRPPER_OID_INDEX_ID_NBUCKETS 8
#define FOREIGN_SERVER_NAME_INDEX_ID_NBUCKETS 32
#define FOREIGN_SERVER_OID_INDEX_ID_NBUCKETS 32
#define FOREIGN_TABLE_REL_ID_INDEX_ID_NBUCKETS 128
#define CLIENT_LOGIC_GLOBAL_SETTING_NAME_INDEX_ID_NBUCKETS 128
#define CLIENT_LOGIC_GLOBAL_SETTING_OID_INDEX_ID_NBUCKETS 128
#define CLIENT_LOGIC_PROC_FUNC_ID_INDEX_ID_NBUCKETS 128
#define CLIENT_LOGIC_PROC_OID_INDEX_ID_NBUCKETS 128
#define GS_JOB_ARGUMENT_NAME_INDEX_ID_NBUCKETS 128
#define GS_JOB_ARGUMENT_POSITION_INDEX_ID_NBUCKETS 128
#define GS_JOB_ATTRIBUTE_NAME_INDEX_ID_NBUCKETS 128
#define GS_OPT_MODEL_NAME_INDEX_ID_NBUCKETS 4
#define RESOURCE_POOL_NAME_INDEX_ID_NBUCKETS 256
#define RESOURCE_POOL_OID_INDEX_ID_NBUCKETS 256
#define APP_WORKLOAD_GROUP_MAPPING_NAME_INDEX_ID_NBUCKETS 256
#define APP_WORKLOAD_GROUP_MAPPING_OID_INDEX_ID_NBUCKETS 256
#define SUBSCRIPTION_NAME_INDEX_ID_NBUCKETS 4
#define SUBSCRIPTION_OID_INDEX_ID_NBUCKETS 4
#define PUBLICATION_REL_MAP_INDEX_ID_NBUCKETS 64
#define SYNONYM_OID_INDEX_ID_NBUCKETS 64
#define SYNONYM_NAME_NSP_INDEX_ID_NBUCKETS 64
#define TS_CONFIG_MAP_INDEX_ID_NBUCKETS 4
#define TS_CONFIG_NAME_NSP_INDEX_ID_NBUCKETS 16
#define TS_CONFIG_OID_NSP_INDEX_ID_NBUCKETS 16
#define TS_DERECTORY_NAME_NSP_INDEX_ID_NBUCKETS 16
#define TS_DERECTORY_OID_INDEX_ID_NBUCKETS 16
#define TS_PARSE_NAME_NSP_INDEX_ID_NBUCKETS 4
#define TS_PARSE_OID_INDEX_ID_NBUCKETS 4
#define TS_TEMPLATE_NAME_NSP_INDEX_ID_NBUCKETS 16
#define TS_TEMPLATE_OID_INDEX_ID_NBUCKETS 16
#define PUBLICATION_NAME_INDEX_ID_NBUCKETS 8
#define PUBLICATION_OID_INDEX_ID_NBUCKETS 8
#define UID_REL_ID_INDEX_ID_NBUCKETS 64
#define DB_PRIVILEGE_OID_INDEX_ID_NBUCKETS 128
#define DB_PRIVILEGE_ROLE_ID_INDEX_ID_NBUCKETS 1024
#define DB_PRIVILEGE_ROLE_ID_PRIVILEGE_TYPE_INDEX_ID_NBUCKETS 128

#endif


#endif /* MEMORY_LITE_H */
