--
-- openGauss database dump
--

SET statement_timeout = 0;
SET xmloption = content;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET session_replication_role = replica;
SET client_min_messages = warning;
SET dolphin.sql_mode = 'sql_mode_full_group,pipes_as_concat,ansi_quotes,pad_char_to_full_length';

SET search_path = public;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: test1; Type: TABLE; Schema: public; Owner: gauss; Tablespace: 
--

CREATE TABLE test1 (
    a integer,
    b text
)
WITH (orientation=row, compression=no);


ALTER TABLE public.test1 OWNER TO gauss;

--
-- Data for Name: test1; Type: TABLE DATA; Schema: public; Owner: gauss
--

COPY public.test1 (a, b) FROM stdin;
1	one
2	two
\.
;

--
-- Name: mysub; Type: SUBSCRIPTION; Schema: -; Owner: gauss
--

CREATE SUBSCRIPTION mysub CONNECTION 'dbname=dump_db user=gauss password=encryptOptjE2MXqiXDNgPvWxcN5Aquu7xei4bJNFcxJodbu8jH3GC9i31q1H8plPam0fqj39x  host=127.0.0.1,127.0.0.1,127.0.0.1 port=25800,25803,25806' PUBLICATION mypub WITH (enabled = false, slot_name = 'mysub');


ALTER SUBSCRIPTION mysub OWNER TO gauss;

--
-- Name: public; Type: ACL; Schema: -; Owner: gauss
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM gauss;
GRANT CREATE,USAGE ON SCHEMA public TO gauss;
GRANT USAGE ON SCHEMA public TO PUBLIC;


--
-- openGauss database dump complete
--

