create database s_test_pg_identity dbcompatibility 'D';
\c s_test_pg_identity
create extension shark;
--## create table
-- error
CREATE TABLE test_t1 (a serial GENERATED ALWAYS AS IDENTITY, b text);
-- error
CREATE TABLE test_t1 (a int GENERATED ALWAYS AS IDENTITY default 3, b text);
-- error
CREATE TABLE test_t1 (id int1 GENERATED ALWAYS AS IDENTITY (START WITH 44) NULL); 
CREATE TABLE test_t1 (id int1 NULL GENERATED ALWAYS AS IDENTITY (START WITH 44)); 
-- error
CREATE TABLE par_row_t1 (a int GENERATED ALWAYS AS IDENTITY, b text) partition by range (a)
(
    partition par_row_t1_p0 values less than(10),
    partition par_row_t1_p3 values less than (maxvalue)
);
CREATE temp TABLE test_t4 (a int GENERATED ALWAYS AS IDENTITY, b text);

-- success
CREATE TABLE test_t1 (a int GENERATED ALWAYS AS IDENTITY, b text);
CREATE TABLE test_t2 (a int GENERATED BY DEFAULT AS IDENTITY, b text);
CREATE TABLE test_t3 (id int1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 44));
\d+ test_t1
\d+ test_t2
select pg_get_tabledef('test_t3'::regclass);

-- identity sequence options
CREATE TABLE test_t5 (a int2 GENERATED ALWAYS AS IDENTITY (START WITH 10 MAXVALUE 30 MINVALUE 12), b text); -- error
CREATE TABLE test_t5 (a int2 GENERATED ALWAYS AS IDENTITY (START WITH 10 MAXVALUE 30 MINVALUE 9), b text); -- success
\d+ test_t5;
select start_value, max_value, min_value, increment_by from test_t5_a_seq;
INSERT INTO test_t5 DEFAULT VALUES; -- success
INSERT INTO test_t5 OVERRIDING SYSTEM VALUE VALUES(8, 'xxxx'); -- success
SELECT * FROM test_t5 order by 1, 2;
CREATE TABLE test_t6 (a int2 GENERATED ALWAYS AS IDENTITY (START WITH 11 NOMAXVALUE MINVALUE 9), b text); -- success
\d+ test_t6;
select start_value, max_value, min_value, increment_by from test_t6_a_seq;
CREATE TABLE test_t7 (a int2 GENERATED ALWAYS AS IDENTITY (START WITH 12 MAXVALUE 15 INCREMENT 2 NOMINVALUE), b text); -- success
\d+ test_t7;
select start_value, max_value, min_value, increment_by from test_t7_a_seq;
INSERT INTO test_t7 DEFAULT VALUES; -- success
INSERT INTO test_t7 DEFAULT VALUES; -- success
INSERT INTO test_t7 DEFAULT VALUES; -- error
ALTER TABLE test_t7 ALTER COLUMN a RESTART;
select start_value, max_value, min_value, increment_by from test_t7_a_seq;
INSERT INTO test_t7 DEFAULT VALUES; -- success
select * from test_t7 order by 1, 2;

DROP TABLE test_t1, test_t2, test_t3, test_t5, test_t6, test_t7;

CREATE TABLE itest1 (a int generated by default as identity, b text);
CREATE TABLE itest2 (a bigint generated always as identity, b text);
CREATE TABLE itest3 (a smallint generated by default as identity (start with 7 increment by 5), b text);
ALTER TABLE itest3 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;  -- error

SELECT table_name, column_name, column_default, is_nullable, is_identity, identity_generation FROM information_schema.columns WHERE table_name LIKE 'itest_' ORDER BY 1, 2;
-- internal sequences should not be shown here
SELECT sequence_name FROM information_schema.sequences WHERE sequence_name LIKE 'itest%';
-- invalid column type
CREATE TABLE itest_err_1 (a text generated by default as identity);
-- duplicate identity
CREATE TABLE itest_err_2 (a int generated always as identity generated by default as identity);
-- cannot have default and identity
CREATE TABLE itest_err_3 (a int default 5 generated by default as identity);
-- cannot combine serial and identity
CREATE TABLE itest_err_4 (a serial generated by default as identity);

--## insert/update OVERRIDING tests
INSERT INTO itest1 DEFAULT VALUES;
INSERT INTO itest1 DEFAULT VALUES;
INSERT INTO itest2 DEFAULT VALUES;
INSERT INTO itest2 DEFAULT VALUES;
INSERT INTO itest3 DEFAULT VALUES;
INSERT INTO itest3 DEFAULT VALUES;

SELECT * FROM itest1 order by a;
SELECT * FROM itest2 order by a;
SELECT * FROM itest3 order by a;

INSERT INTO itest1 VALUES (10, 'xyz');
INSERT INTO itest1 OVERRIDING USER VALUE VALUES (10, 'xyz');

SELECT * FROM itest1 order by a;

INSERT INTO itest2 VALUES (10, 'xyz'); -- error
INSERT INTO itest2 OVERRIDING SYSTEM VALUE VALUES (10, 'xyz');

SELECT * FROM itest2;

CREATE TABLE test_t1 (a int GENERATED ALWAYS AS IDENTITY, b text);
INSERT INTO test_t1 VALUES('xxxx'); -- error
INSERT INTO test_t1(b) VALUES('xxxx'); -- success
INSERT INTO test_t1(a, b) VALUES(1, 'xxxx'); -- error
INSERT INTO test_t1 VALUES(1, 'xxxx'); -- error
INSERT INTO test_t1 VALUES(DEFAULT, 'xxxx'); -- success
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(1111, 'xx'); -- success
INSERT INTO test_t1 OVERRIDING USER VALUE VALUES(1111, 'xxxx');  -- success
INSERT INTO test_t1(a, b) OVERRIDING USER VALUE VALUES(DEFAULT, 'xxxx'); -- success
INSERT INTO test_t1(a, b) OVERRIDING SYSTEM VALUE VALUES(1, 'xxxx'); -- success
INSERT INTO test_t1(a, b) select 1, 'xxxxx'; -- error
INSERT INTO test_t1(a, b) OVERRIDING USER VALUE select 1, 'xxxxx'; -- success
INSERT INTO test_t1(a, b) OVERRIDING SYSTEM VALUE select 12222, 'xxxxx'; -- success
SELECT * FROM test_t1 ORDER BY a;

CREATE TABLE test_t2 (a int GENERATED BY DEFAULT AS IDENTITY, b text);
INSERT INTO test_t2 VALUES('xxxx'); -- error
INSERT INTO test_t2(b) VALUES('xxxx'); -- success
INSERT INTO test_t2(a, b) VALUES(1, 'xxxx'); -- success
INSERT INTO test_t2 VALUES(1, 'xxxx'); -- success
INSERT INTO test_t2 VALUES(DEFAULT, 'xxxx'); -- success
INSERT INTO test_t2 OVERRIDING SYSTEM VALUE VALUES(1111, 'xx'); -- success
INSERT INTO test_t2 OVERRIDING USER VALUE VALUES(1111, 'xxxx');  -- success
INSERT INTO test_t2(a, b) OVERRIDING USER VALUE VALUES(DEFAULT, 'xxxx'); -- success
INSERT INTO test_t2(a, b) OVERRIDING SYSTEM VALUE VALUES(1, 'xxxx'); -- success
INSERT INTO test_t2(a, b) select 1, 'xxxxx'; -- success
INSERT INTO test_t2(a, b) OVERRIDING USER VALUE select 1, 'xxxxx'; -- success
INSERT INTO test_t2(a, b) OVERRIDING SYSTEM VALUE select 12222, 'xxxxx'; -- success
SELECT * FROM test_t2 ORDER BY a;

DROP TABLE test_t1, test_t2;

--## inline view tests
CREATE TABLE test_t1 (a int GENERATED ALWAYS AS IDENTITY, b text, c int);
CREATE TABLE test_t2 (a int GENERATED ALWAYS AS IDENTITY, b text, c int);
INSERT INTO test_t1 DEFAULT VALUES;
INSERT INTO test_t2 DEFAULT VALUES;
-- insert
INSERT INTO (SELECT a, b FROM test_t1 WHERE a = 1) sup
    SELECT 2, 'inline view'; -- error
INSERT INTO (SELECT a, b FROM test_t1 WHERE a = 1) sup
    OVERRIDING SYSTEM VALUE SELECT 22, 'inline view'; -- success
INSERT INTO (SELECT a, b FROM test_t1 WHERE a = 1) sup
    OVERRIDING USER VALUE SELECT 12, 'inline view'; -- success
SELECT * FROM test_t1 order by 1, 2;

-- update
UPDATE (SELECT a, b FROM test_t1 WHERE a = 1) sup -- SET TO DEFAULT is not supported for subquery "sup"
    SET sup.a = 2; -- error
UPDATE (SELECT a, b FROM test_t1 WHERE a = 1) sup
    SET sup.a = DEFAULT; -- error
UPDATE (SELECT a, b FROM test_t1 WHERE a = 12) sup
    SET sup.a = DEFAULT, b = 'inline view updated'; -- error
SELECT * FROM test_t1 order by 1, 2;

UPDATE (SELECT a, b FROM test_t1 WHERE a = 1) sup
    SET sup.a = DEFAULT; -- error
UPDATE (SELECT a, b FROM test_t1 WHERE a = 1) sup
    SET sup.b = 'inline view updated'; -- success
SELECT * FROM test_t1 order by 1, 2;

DROP TABLE test_t1, test_t2;

-- --## multi insert tests
-- CREATE TABLE test_t1 (a int GENERATED ALWAYS AS IDENTITY, b text);
-- CREATE TABLE test_t2 (a int GENERATED BY DEFAULT AS IDENTITY, b text);
-- -- error
-- INSERT ALL
--     INTO test_t1 (a, b) VALUES (val1, val2)
--     INTO test_t2 (a, b) VALUES (val1, val2)
-- SELECT 1 as val1, 'x1' as val2;
-- -- success
-- INSERT ALL
--     INTO test_t1 (a, b) OVERRIDING USER VALUE VALUES (val1, val2)
--     INTO test_t2 (a, b) VALUES (val1, val2)
-- SELECT 2 as val1, 'x1' as val2;
-- -- success
-- INSERT ALL
--     INTO test_t1 (a, b) OVERRIDING SYSTEM VALUE VALUES (val1, val2)
--     INTO test_t2 (a, b) VALUES (val1, val2)
-- SELECT 3 as val1, 'x2' as val2;
-- -- success
-- INSERT ALL
--     INTO test_t1 (a, b) OVERRIDING SYSTEM VALUE VALUES (DEFAULT, val2)
--     INTO test_t2 (a, b) VALUES (val1, val2)
-- SELECT 4 as val1, 'x3' as val2;
-- -- success
-- INSERT ALL
--     INTO test_t1 (a, b) VALUES (DEFAULT, val2)
--     INTO test_t2 (a, b) VALUES (DEFAULT, val2)
-- SELECT 5 as val1, 'x4' as val2;
-- -- success
-- INSERT ALL
--     INTO test_t1 (a, b) VALUES (DEFAULT, val2)
--     INTO test_t2 (a, b) OVERRIDING USER VALUE VALUES (999, val2)
-- SELECT 6 as val1, 'x5' as val2;
-- -- success
-- INSERT ALL
--     INTO test_t1 (b) VALUES (DEFAULT, val2)
--     INTO test_t2 (b) VALUES (DEFAULT, val2)
-- SELECT 7 as val1, 'x6' as val2;

-- SELECT * FROM test_t1 ORDER BY b;
-- SELECT * FROM test_t2 ORDER BY b;

-- DROP TABLE test_t1, test_t2;

--## upserts tests
CREATE TABLE test_t1 (a int PRIMARY KEY GENERATED ALWAYS AS IDENTITY , b text);
INSERT INTO test_t1 VALUES (DEFAULT, default);
SELECT * FROM test_t1;
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(1, 'xxxx'); -- error
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(1, 'setb') ON DUPLICATE KEY UPDATE b = 'setb'; -- success
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(1, 'nothing') ON DUPLICATE KEY UPDATE NOTHING; -- success
SELECT * FROM test_t1 order by 1, 2; -- 1, setb
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(1, 'nothing') ON DUPLICATE KEY UPDATE a = 2; -- error
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(1, 'seta') ON DUPLICATE KEY UPDATE b = 'seta';  -- success
SELECT * FROM test_t1 order by 1, 2; -- 1, seta
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(1, 'seta') ON DUPLICATE KEY UPDATE b = 'setc', a = DEFAULT; -- error
SELECT * FROM test_t1 order by 1, 2; -- 1, seta
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(2, 'test1'); -- success
INSERT INTO test_t1 OVERRIDING USER VALUE VALUES(1111, 'test1'); -- error
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(3, 'test1'); -- success
INSERT INTO test_t1 OVERRIDING USER VALUE VALUES(1111, 'test1') ON DUPLICATE KEY UPDATE b = 'w3' WHERE a = 3; -- success
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(4, 'test1'); -- success
INSERT INTO test_t1 OVERRIDING USER VALUE VALUES(1111, 'test1') ON DUPLICATE KEY UPDATE a = 5 WHERE a = 4; -- error, 未自增
SELECT * FROM test_t1 order by 1, 2;
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(5, 'test1'); -- success
INSERT INTO test_t1 OVERRIDING USER VALUE VALUES(1111, 'test1') ON DUPLICATE KEY UPDATE b = 'w5', a = DEFAULT WHERE a = 5; -- error, 未自增
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(6, 'test1'); -- success
INSERT INTO test_t1 OVERRIDING USER VALUE VALUES(1111, 'test1') ON DUPLICATE KEY UPDATE b = 'w6' WHERE a = 4; -- success

SELECT * FROM test_t1 order by 1, 2;

CREATE TABLE test_t2 (a int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, b text);
INSERT INTO test_t2 DEFAULT VALUES;
SELECT * FROM test_t2;
INSERT INTO test_t2 OVERRIDING SYSTEM VALUE VALUES(1, 'xxxx'); -- error
INSERT INTO test_t2 OVERRIDING SYSTEM VALUE VALUES(1, 'setb') ON DUPLICATE KEY UPDATE b = 'setb'; -- success
SELECT * FROM test_t2 order by 1, 2;
INSERT INTO test_t2 OVERRIDING SYSTEM VALUE VALUES(1, 'setc') ON DUPLICATE KEY UPDATE a = 2; -- error
INSERT INTO test_t2 OVERRIDING SYSTEM VALUE VALUES(1, 'setc') ON DUPLICATE KEY UPDATE a = DEFAULT, b = 'setc'; -- error
SELECT * FROM test_t2 order by 1, 2; -- 1, setb
INSERT INTO test_t2 OVERRIDING USER VALUE VALUES(2, 'test1'); -- success
INSERT INTO test_t2 OVERRIDING USER VALUE VALUES(2, 'test2') ON DUPLICATE KEY UPDATE b = 'test3'; -- success
SELECT * FROM test_t2 order by 1, 2; -- 
INSERT INTO test_t2 OVERRIDING SYSTEM VALUE VALUES(1, 'test2') ON DUPLICATE KEY UPDATE a = 3; -- error
INSERT INTO test_t2 OVERRIDING SYSTEM VALUE VALUES(1, 'test2') ON DUPLICATE KEY UPDATE a = DEFAULT, b = 'test2'; -- error
SELECT * FROM test_t2 order by 1, 2;

DROP TABLE test_t1, test_t2;

--## returning tests
CREATE TABLE test_t1 (a int GENERATED ALWAYS AS IDENTITY(START WITH 10) PRIMARY KEY, b text);
CREATE TABLE test_t2 (a int GENERATED BY DEFAULT AS IDENTITY(START WITH 12) PRIMARY KEY, b text);
INSERT INTO test_t1 DEFAULT VALUES RETURNING a;
INSERT INTO test_t2 DEFAULT VALUES RETURNING a;
DROP TABLE test_t1, test_t2;

--## UPDATE tests
UPDATE itest1 SET a = 101 WHERE a = 1;
UPDATE itest1 SET a = DEFAULT WHERE a = 2;
UPDATE itest1 SET b = 'test' where a=101;
SELECT * FROM itest1 order by 1, 2;

UPDATE itest2 SET a = 101 WHERE a = 1; -- error
UPDATE itest2 SET a = DEFAULT WHERE a = 2;
UPDATE itest2 SET b = 'test' where a=101;
SELECT * FROM itest2 order by 1, 2;

--## merge tests
-- when not matched insert
create table target_table (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name varchar(50),
    age int
);
create table source_table (id int, name varchar(50), age int);
insert into source_table values (10, 'zliu', 28), (11, 'sqi', 30);
-- expected: success. let id generated by system.
merge into target_table AS t using source_table AS s ON t.id = s.id
when not matched then
    insert (name, age) values (s.name, s.age);
-- expected: error
merge into target_table AS t using source_table AS s ON t.id = s.id
when not matched then
    insert (id, name, age) values (1, 'error', 21);
-- expected: success
merge into target_table AS t using source_table AS s ON t.id = s.id
when not matched then
    insert (id, name, age) OVERRIDING USER VALUE values (1, 'success', 22); -- 3
-- expected: error
merge into target_table AS t using source_table AS s ON t.id = s.id
when not matched then
    insert (id, name, age) OVERRIDING SYSTEM VALUE values (2, 'error', 23);
-- expected: success
merge into target_table AS t using source_table AS s ON t.id = s.id
when not matched then
    insert (id, name, age) OVERRIDING SYSTEM VALUE values (3, 'success', 24);
-- expected: success
merge into target_table AS t using source_table AS s ON t.id = s.id
when not matched then
    insert (id, name, age) OVERRIDING USER VALUE values (3, 'success', 25);
-- expected: success
merge into target_table AS t using source_table AS s ON t.id = s.id
when not matched then
    insert (id, name, age) OVERRIDING SYSTEM VALUE values (DEFAULT, 'success', 26);
-- expected: success
merge into target_table AS t using source_table AS s ON t.id = s.id
when not matched then
    insert (id, name, age) OVERRIDING USER VALUE values (DEFAULT, 'success', 27);
SELECT * from target_table order by id;
DROP TABLE target_table, source_table;

-- when matched update
create table target_table (
    id int  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name varchar(50), 
    age int
);
create table source_table (id int, name varchar(50), age int);
insert into source_table values (1, 'zliu', 28), (2, 'sqi', 30);
-- success
insert into target_table default values;
merge into target_table AS t using source_table AS s ON t.id = s.id
WHEN MATCHED THEN
  UPDATE SET name = s.name, age = s.age + 1;
-- error
insert into target_table default values;
merge into target_table AS t using source_table AS s ON t.id = s.id
WHEN MATCHED THEN
  UPDATE SET id = s.id + 1;
-- error
merge into target_table AS t using source_table AS s ON t.id = s.id
WHEN MATCHED THEN
  UPDATE SET id = DEFAULT, name = s.name, age = s.age + 1;

SELECT * from target_table;
DROP TABLE target_table, source_table;

-- CTE with modifying clause
CREATE TABLE test_t1 (a int GENERATED ALWAYS AS IDENTITY(START WITH 10) PRIMARY KEY, b text);
CREATE TABLE test_t2 (a int GENERATED BY DEFAULT AS IDENTITY(START WITH 12) PRIMARY KEY, b text);

-- error
WITH xxx AS (
    INSERT INTO test_t1(a, b) VALUES(1, 'xxxx') RETURNING a
) select * from xxx;
-- success
WITH xxx AS (
    INSERT INTO test_t2(a, b) VALUES(1, 'x1') RETURNING a, b
) select * from xxx;
-- success
WITH xxx AS (
    INSERT INTO test_t1(a, b) OVERRIDING SYSTEM VALUE VALUES(1, 'x1') RETURNING a, b
) select * from xxx;
-- success
WITH xxx AS (
    INSERT INTO test_t1(a, b) OVERRIDING USER VALUE VALUES(3, 'x2') RETURNING a, b
) select * from xxx; -- should be 2
-- error
WITH xxx AS (
    UPDATE test_t1 SET a = 3 RETURNING a, b
) select * from xxx;
-- error
WITH xxx AS (
    UPDATE test_t2 SET a = 3 RETURNING a, b
) select * from xxx;
-- success
WITH xxx AS (
    UPDATE test_t1 SET a = DEFAULT, b = 't1_updated' RETURNING a, b
) select * from xxx;
-- success
WITH xxx AS (
    UPDATE test_t2 SET a = DEFAULT, b = 't2_updated' RETURNING a, b
) select * from xxx;

DROP TABLE test_t1, test_t2;

--## alter table
CREATE TABLE itest4 (a int, b text);
ALTER TABLE itest4 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;  -- error, requires NOT NULL
ALTER TABLE itest4 ALTER COLUMN a SET NOT NULL;
ALTER TABLE itest4 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;  -- ok
\d+ itest4

ALTER TABLE itest4 ALTER COLUMN a DROP NOT NULL;  -- error, disallowed
ALTER TABLE itest4 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;  -- error, already set
ALTER TABLE itest4 ALTER COLUMN b ADD GENERATED ALWAYS AS IDENTITY;  -- error, wrong data type

INSERT INTO itest4 DEFAULT VALUES;
INSERT INTO itest4 DEFAULT VALUES;
SELECT * FROM itest4;

-- alter add column
CREATE TABLE itest4_1 (a int, b text);
ALTER TABLE itest4_1 ADD COLUMN c text GENERATED ALWAYS AS IDENTITY; -- error
ALTER TABLE itest4_1 ADD COLUMN c int GENERATED ALWAYS AS IDENTITY; -- success
\d+ itest4_1
INSERT INTO itest4_1 DEFAULT VALUES;
INSERT INTO itest4_1 (c, a, b) VALUES(1, 2, 'x1'); -- error
INSERT INTO itest4_1 (c, a, b) OVERRIDING SYSTEM VALUE VALUES(111, 2, 'x2'); -- success
INSERT INTO itest4_1 (c, a, b) VALUES(DEFAULT, 2, 'x3'); -- success
SELECT c, a, b FROM itest4_1 order by c, b, a;

CREATE TABLE itest4_2 (a int, b text);
ALTER TABLE itest4_2 ADD COLUMN c text GENERATED BY DEFAULT AS IDENTITY; -- error
ALTER TABLE itest4_2 ADD COLUMN c int GENERATED BY DEFAULT AS IDENTITY; -- success
ALTER TABLE itest4_2 ALTER COLUMN a ADD GENERATED BY DEFAULT AS IDENTITY;
\d+ itest4_2
INSERT INTO itest4_2 DEFAULT VALUES;
INSERT INTO itest4_2 (c, a, b) VALUES(1, 2, 'x1'); -- success
INSERT INTO itest4_2 (c, a, b) OVERRIDING SYSTEM VALUE VALUES(111, 2, 'x2'); -- success
INSERT INTO itest4_2 (c, a, b) VALUES(DEFAULT, 2, 'x3'); -- success
SELECT c, a, b FROM itest4_2 order by c, b, a;

DROP TABLE itest4_1, itest4_2;

-- for later
ALTER TABLE itest4 ALTER COLUMN b SET DEFAULT '';

-- DROP IDENTITY tests
ALTER TABLE itest4 ALTER COLUMN b DROP IDENTITY;  -- error
ALTER TABLE itest4 ALTER COLUMN a DROP IDENTITY;
INSERT INTO itest4 VALUES (NULL, 'nullable');
ALTER TABLE itest4 ALTER COLUMN a DROP IDENTITY IF EXISTS;  -- noop

INSERT INTO itest4 DEFAULT VALUES;  -- fails because NOT NULL is not dropped
ALTER TABLE itest4 ALTER COLUMN a DROP NOT NULL;
INSERT INTO itest4 DEFAULT VALUES;
SELECT * FROM itest4;
-- check that sequence is removed
SELECT sequence_name FROM itest4_a_seq;

-- fail, not allowed for identity columns
ALTER TABLE itest1 ALTER COLUMN a SET DEFAULT 1;
ALTER TABLE itest1 ALTER COLUMN a DROP DEFAULT;

-- fail, not allowed, already has a default
CREATE TABLE itest5 (a serial, b text);
ALTER TABLE itest5 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;

--success
ALTER TABLE itest5 DROP COLUMN a;
SELECT sequence_name FROM itest5_a_seq;
DROP TABLE itest5;

-- not supported
\d+ itest3
ALTER TABLE itest3 ALTER COLUMN a TYPE int;
ALTER TABLE itest3 ALTER COLUMN a TYPE text;

-- ALTER COLUMN ... SET
CREATE TABLE itest6 (a int GENERATED ALWAYS AS IDENTITY, b text);
\d+ itest6
\d+ itest6_a_seq
INSERT INTO itest6 DEFAULT VALUES;
INSERT INTO itest6 DEFAULT VALUES;
SELECT * FROM itest6;

ALTER TABLE itest6 ALTER COLUMN a SET GENERATED BY DEFAULT SET INCREMENT BY 2 SET START WITH 100 RESTART;
\d+ itest6
\d+ itest6_a_seq
INSERT INTO itest6 DEFAULT VALUES;
INSERT INTO itest6 DEFAULT VALUES;
SELECT * FROM itest6;

SELECT table_name, column_name, is_identity, identity_generation FROM information_schema.columns WHERE table_name = 'itest6' order by 1,2,3,4;

ALTER TABLE itest6 ALTER COLUMN b SET INCREMENT BY 2;  -- fail, not identity


-- --## multiple steps in ALTER TABLE
-- cuase transformAlterTableStmt will analysis AT_Column and AT_AddIdentity
-- at same time, when AT_AddIdentity, new column has not been created yet.
-- CREATE TABLE itest5 (a int, b text);
-- ALTER TABLE itest5
--   ADD COLUMN f21 int NULL,
--   ALTER COLUMN f21 ADD GENERATED ALWAYS AS IDENTITY;

-- ALTER TABLE itest5
--   ADD COLUMN f22 int NOT NULL,
--   ALTER COLUMN f22 ADD GENERATED ALWAYS AS IDENTITY;

--## sequence
-- prohibited direct modification of sequence
ALTER SEQUENCE itest6_a_seq OWNED BY NONE;
CREATE SEQUENCE sequence_testx OWNED BY pg_class_oid_index.oid;  -- not a table
CREATE SEQUENCE my_int_seq;
-- not supported 'AS' option
CREATE SEQUENCE my_int_seq AS INTEGER;
-- not supported 'SEQUENCE NAME' option
ALTER SEQUENCE my_int_seq SEQUENCE NAME my_int_seq_1;

-- alter sequence set schame
create schame seq1;
create sequence s1;
-- error
alter sequence s1 set schame seq1;
alter table seq1 set schame seq1;

--## truncate
CREATE TABLE truncate_b (id int GENERATED ALWAYS AS IDENTITY (START WITH 44));

INSERT INTO truncate_b DEFAULT VALUES;
INSERT INTO truncate_b DEFAULT VALUES;
SELECT * FROM truncate_b;

TRUNCATE truncate_b;

INSERT INTO truncate_b DEFAULT VALUES;
INSERT INTO truncate_b DEFAULT VALUES;
SELECT * FROM truncate_b;

-- not supported 
TRUNCATE truncate_b RESTART IDENTITY;

--## create table like
CREATE TABLE test_like_id_1 (a int GENERATED ALWAYS AS IDENTITY, b text);
\d test_like_id_1
INSERT INTO test_like_id_1 (b) VALUES ('b1');
SELECT * FROM test_like_id_1;

CREATE TABLE test_like_id_2 (LIKE test_like_id_1);
\d test_like_id_2
INSERT INTO test_like_id_2 (b) VALUES ('b2');
SELECT * FROM test_like_id_2;  -- identity was not copied

CREATE TABLE test_like_id_3 (LIKE test_like_id_1 INCLUDING IDENTITY);
\d test_like_id_3
INSERT INTO test_like_id_3 (b) VALUES ('b3');
SELECT * FROM test_like_id_3;  -- identity was copied and applied

CREATE TABLE test_like_id_4 (like test_like_id_1 INCLUDING DEFAULTS INCLUDING IDENTITY);
\d test_like_id_4
INSERT INTO test_like_id_4 (b) VALUES ('b3');
SELECT * FROM test_like_id_4;  -- identity was copied and applied

-- not copy, because no identity column
CREATE TABLE par_row_t1 (a int, b text) partition by range (a)
(
    partition par_row_t1_p0 values less than(10),
    partition par_row_t1_p3 values less than (maxvalue)
);
CREATE TABLE test_lik3_v (LIKE par_row_t1 INCLUDING IDENTITY);

DROP TABLE test_like_id_2, test_like_id_3, test_like_id_4, par_row_t1, test_lik3_v;

--## select into
-- not copy identity
SELECT a, b into test_like_id_5 from test_like_id_1;
\d test_like_id_5
INSERT INTO test_like_id_5 (b) VALUES ('b1');
SELECT * FROM test_like_id_5;

DROP TABLE test_like_id_1, test_like_id_5;

--## test views
CREATE TABLE itest10 (a int generated by default as identity, b text);
CREATE TABLE itest11 (a int generated always as identity, b text);

CREATE VIEW itestv10 AS SELECT * FROM itest10;
CREATE VIEW itestv11 AS SELECT * FROM itest11;

INSERT INTO itestv10 DEFAULT VALUES;
INSERT INTO itestv10 DEFAULT VALUES;

INSERT INTO itestv11 DEFAULT VALUES;
INSERT INTO itestv11 DEFAULT VALUES;

SELECT * FROM itestv10;
SELECT * FROM itestv11;

INSERT INTO itestv10 VALUES (10, 'xyz');
INSERT INTO itestv10 OVERRIDING USER VALUE VALUES (11, 'xyz');

SELECT * FROM itestv10 order by 1, 2;

INSERT INTO itestv11 VALUES (10, 'xyz');
INSERT INTO itestv11 OVERRIDING SYSTEM VALUE VALUES (11, 'xyz');

SELECT * FROM itestv11 order by 1, 2;

CREATE TABLE itest12 (a int NOT NULL, b text);
CREATE VIEW itestv12 AS SELECT * FROM itest12;
ALTER VIEW itestv12 alter column a add generated by default as identity; -- error
ALTER VIEW itestv12 alter column a SET NOT NULL; -- error
ALTER VIEW itestv12 alter column a RESTART; -- error
ALTER VIEW itestv12 alter column a drop identity; -- error
\d+ itestv12;

DROP VIEW itestv12;
DROP TABLE itest12;

--## ALTER xxx alter column add/set/drop identity
create sequence saaa;
ALTER SEQUENCE saaa alter column max_value add generated always as identity; -- error
create table test_t1 (a int);
create materialized view mv as select * from test_t1;
ALTER MATERIALIZED VIEW mv alter column a add generated by default as identity; -- error

DROP TABLE test_t1;
DROP sequence saaa;
DROP MATERIALIZED VIEW mv;

--## inheritance
CREATE TABLE itest7 (a int GENERATED ALWAYS AS IDENTITY (maxvalue 100));
INSERT INTO itest7 DEFAULT VALUES;
SELECT * FROM itest7;

-- identity property is not inherited
CREATE TABLE itest7a (b text) INHERITS (itest7);
\d+ itest7a

-- make column identity in child table
CREATE TABLE itest7b (a int);
CREATE TABLE itest7c (a int GENERATED ALWAYS AS IDENTITY) INHERITS (itest7b);
INSERT INTO itest7c DEFAULT VALUES;
SELECT * FROM itest7c;

CREATE TABLE itest7d (a int not null);
CREATE TABLE itest7e () INHERITS (itest7d);
ALTER TABLE itest7d ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE itest7d ADD COLUMN b int GENERATED ALWAYS AS IDENTITY;  -- error

SELECT table_name, column_name, is_nullable, is_identity, identity_generation FROM information_schema.columns WHERE table_name LIKE 'itest7%' ORDER BY 1, 2;

-- These ALTER TABLE variants will not recurse.
ALTER TABLE itest7 ALTER COLUMN a SET GENERATED BY DEFAULT;
ALTER TABLE itest7 ALTER COLUMN a RESTART;
ALTER TABLE itest7 ALTER COLUMN a DROP IDENTITY;

--## pbe
CREATE TABLE test_t1 (a int PRIMARY KEY GENERATED ALWAYS AS IDENTITY , b text);
INSERT INTO test_t1 VALUES (DEFAULT, default);
PREPARE p1 AS INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES($1, $2); -- error
PREPARE p2 AS INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES($1, $2) ON DUPLICATE KEY UPDATE b = $3; -- success
EXECUTE p1 (1, 'xxxx');
EXECUTE p2 (1, 'setb', 'setb');
DEALLOCATE p1;
DEALLOCATE p2;
select * from test_t1 order by 1, 2;
DROP TABLE test_t1;

--## partitoned table
CREATE TABLE par_row_t1 (a int, b text) partition by range (a)
(
    partition par_row_t1_p0 values less than(10),
    partition par_row_t1_p3 values less than (maxvalue)
);
ALTER TABLE par_row_t1 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY; -- error
ALTER TABLE par_row_t1 ALTER COLUMN a SET GENERATED BY DEFAULT; -- error
ALTER TABLE par_row_t1 ALTER COLUMN a DROP IDENTITY; -- error
ALTER TABLE par_row_t1 ALTER COLUMN a DROP IDENTITY IF EXISTS; -- error
ALTER TABLE par_row_t1 ADD COLUMN c int GENERATED ALWAYS AS IDENTITY; -- error

DROP TABLE par_row_t1;

--## NUMERIC test
CREATE TABLE test_t1 (a NUMERIC(12, 0) PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1010101010101), b text); -- error
CREATE TABLE test_t1 (a NUMERIC(12, 0) PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 101010101010), b text);
INSERT INTO test_t1 DEFAULT VALUES; -- success
INSERT INTO test_t1 VALUES(101010101010, 'xxxx'); -- error
INSERT INTO test_t1 OVERRIDING SYSTEM VALUE VALUES(10, 'xxxx'); -- success
INSERT INTO test_t1 OVERRIDING USER VALUE VALUES(10, 'xxxx'); -- success
SELECT * from test_t1 order by 1, 2;

DROP TABLE test_t1;

--## ALTER SET IDENTITY tests
CREATE TABLE test_t1 (a int GENERATED ALWAYS AS IDENTITY(START WITH 4) , b text);
\d+ test_t1_a_seq;
ALTER TABLE test_t1 ALTER COLUMN a SET START WITH 10; -- success
ALTER TABLE test_t1 ALTER COLUMN a SET INCREMENT BY 2; -- success
\d+ test_t1_a_seq;
ALTER TABLE test_t1 ALTER COLUMN a SET MAXVALUE 3; -- error
ALTER TABLE test_t1 ALTER COLUMN a SET MAXVALUE 20; -- success
ALTER TABLE test_t1 ALTER COLUMN a SET MINVALUE 9; -- error
ALTER TABLE test_t1 ALTER COLUMN a SET MINVALUE 2; -- success
ALTER TABLE test_t1 ALTER COLUMN a SET RESTART; -- error
ALTER TABLE test_t1 ALTER COLUMN a SET NOCYCLE; -- success
ALTER TABLE test_t1 ALTER COLUMN a SET CACHE 10; -- success
\d+ test_t1_a_seq;
INSERT INTO test_t1 DEFAULT VALUES;
INSERT INTO test_t1 DEFAULT VALUES;
SELECT * FROM test_t1 order by 1, 2;
ALTER TABLE test_t1 ALTER COLUMN a SET NOMAXVALUE; -- success
ALTER TABLE test_t1 ALTER COLUMN a SET NOMINVALUE; -- success
ALTER TABLE test_t1 ALTER COLUMN a RESTART WITH 10; -- success
ALTER TABLE test_t1 ALTER COLUMN a RESTART 11111; -- success
ALTER TABLE test_t1 ALTER COLUMN a SET RESTART 11; -- error
\d+ test_t1_a_seq;
INSERT INTO test_t1 DEFAULT VALUES;
INSERT INTO test_t1 DEFAULT VALUES;
SELECT * FROM test_t1 order by 1, 2;

-- numeric/large sequence
create table test_t2 (a int generated always as identity, b int);
alter table test_t2 add column c numeric(20, 0) generated by default as identity;
alter table test_t2 alter column c set generated always set start with 10;
\d+ test_t2

DROP sequence test_t1_a_seq; -- error
DROP TABLE test_t1, test_t2;

--## privileges
CREATE USER regress_user1 WITH PASSWORD 'Gauss@123';
CREATE TABLE itest8 (a int GENERATED ALWAYS AS IDENTITY, b text);
GRANT SELECT, INSERT ON itest8 TO regress_user1;
SET ROLE regress_user1 PASSWORD 'Gauss@123';
INSERT INTO itest8 DEFAULT VALUES;
SELECT * FROM itest8;
RESET ROLE;
DROP TABLE itest8;
DROP USER regress_user1;

--## gs_catalog_attribute_records
SELECT attidentity, attnum FROM gs_catalog_attribute_records(1249) ORDER BY attnum LIMIT 1;

--## with identity for d
CREATE TABLE book(bookId int IDENTITY GENERATED BY DEFAULT AS IDENTITY, bookname NVARCHAR(50), author NVARCHAR(50)); -- error
CREATE TABLE book(bookId int IDENTITY, bookname NVARCHAR(50), author NVARCHAR(50), c int GENERATED BY DEFAULT AS IDENTITY); -- error
CREATE TABLE book(bookId int IDENTITY, bookname NVARCHAR(50), author NVARCHAR(50)); -- success
ALTER TABLE book ADD column c int IDENTITY; -- error
ALTER TABLE book ADD column c int GENERATED BY DEFAULT AS IDENTITY; -- error
ALTER TABLE book ADD column c int IDENTITY(1, 20); -- error
ALTER TABLE book ADD column note NVARCHAR(50); -- success
ALTER TABLE book DROP column note; -- success

ALTER TABLE book ALTER column c Add GENERATED BY DEFAULT AS IDENTITY; -- error
ALTER TABLE book ALTER column bookId Add GENERATED BY DEFAULT AS IDENTITY; -- error
ALTER TABLE book ALTER column bookId ADD IDENTITY(1, 20); -- error

ALTER TABLE book ALTER COLUMN bookname SET GENERATED BY DEFAULT; -- error
ALTER TABLE book ALTER COLUMN bookId SET GENERATED BY DEFAULT; -- error

ALTER TABLE book ALTER COLUMN bookId DROP IDENTITY; -- error
ALTER TABLE book ALTER COLUMN bookname DROP IDENTITY; -- error

ALTER TABLE book ALTER COLUMN bookId DROP DEFAULT; -- error
ALTER TABLE book ALTER COLUMN bookId DROP NOT NULL; -- error

ALTER SEQUENCE book_bookid_seq_identity OWNED BY NONE; -- success
ALTER SEQUENCE book_bookid_seq_identity OWNED BY book.bookId; -- success

\d+ book
set identity_insert = off;
INSERT INTO book VALUES (2, 'xxx', 'xxx'); -- error;
INSERT INTO book (bookid, bookname, author) VALUES(11111, 'xxxx', 'xxx'); -- error, turn on identity_insert or use OVERRIDING
INSERT INTO book (bookid, bookname, author) OVERRIDING SYSTEM VALUE VALUES (33, 'xxx', 'xxx'); -- success; -- 33
INSERT INTO book (bookid, bookname, author) OVERRIDING USER VALUE VALUES (11111, 'xxx', 'xxx'); -- success; -- 1
set identity_insert = on;
INSERT INTO book VALUES (44, 'xxx', 'xxx'); -- error;
INSERT INTO book (bookid, bookname, author) OVERRIDING USER VALUE VALUES (11111, 'xxx', 'xxx'); -- success; -- 2
INSERT INTO book (bookid, bookname, author) OVERRIDING SYSTEM VALUE VALUES (55, 'xxx', 'xxx'); -- success; -- 55
set identity_insert = off;
select * from book order by 1, 2;

CREATE TABLE book1(b int1 GENERATED BY DEFAULT AS IDENTITY(START WITH 4), c int GENERATED BY DEFAULT AS IDENTITY (START WITH 5)); -- success
ALTER TABLE book1 ADD column c int IDENTITY; -- error
ALTER TABLE book1 ADD column a int IDENTITY(6, 2); -- success
ALTER TABLE book1 ADD column d int IDENTITY; -- error
insert into book1 values (1, 2, 3); -- error, cam't specify the value of the identity column
set identity_insert = on; -- need to specify column names and turn on identity_insert
insert into book1 values (1, 2, 3); -- error
insert into book1(b, c, a) values (DEFAULT, DEFAULT, DEFAULT); -- success
select * from book1 order by 1, 2, 3;
set identity_insert = off;

select pg_get_tabledef('book'::regclass::oid);
select pg_get_tabledef('book1'::regclass::oid);

\c postgres
DROP DATABASE s_test_pg_identity;
