#-------------------------------------------------------------------------
#
# src/common/backend/utils/mb/conversion_procs/utf8_and_uhc/Makefile
#
#-------------------------------------------------------------------------
subdir = src/common/backend/utils/mb/conversion_procs/utf8_and_uhc
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= utf8_and_uhc

include $(srcdir)/../proc.mk
