#----------------------------------------------------------------------------
#
# openGauss documentation tool makefile
#
# Copyright (c) 2010-2012 Postgres-XC Development Group
#
# common/pgxc/Makefile
#
#----------------------------------------------------------------------------

subdir = src/common/pgxc
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = tools

$(recurse)
