#!/usr/bin/env bash
# Copyright (c) 2022 Huawei Technologies Co.,Ltd.
#
# openGauss is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

# ------------Utils------------
function die() {
    echo -e $1
    exit 1
}

die " \n
     DBMind is no longer installed with the openGauss package by default. \n
     If you need to obtain the latest DBMind installation package,  \n
     please obtain it from the following URL:  \n
                                                 \n
     1. https://gitee.com/opengauss/openGauss-DBMind \n
     2. https://github.com/opengauss-mirror/openGauss-DBMind  \n
                                                              \n
     Report bugs via ai@opengauss.org \n
     "
