#---------------------------------------------------------------------------------------
#
#  IDENTIFICATION
#        src/gausskernel/dbmind/Makefile
#
# ---------------------------------------------------------------------------------------

subdir = src/gausskernel/dbmind
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = kernel db4ai

include $(top_srcdir)/src/gausskernel/common.mk
