/* autogenerated from src/backend/utils/cm_errcodes.txt, do not edit */
/* there is deliberately not an #ifndef ERRCODES_H here */

/* Class c0 - Connection Exception */
#define ERRCODE_CONNECTION_EXCEPTION MAKE_SQLSTATE('c','0','0','0','0')
#define ERRCODE_CONNECTION_DOES_NOT_EXIST MAKE_SQLSTATE('c','0','0','0','1')
#define ERRCODE_CONNECTION_FAILURE MAKE_SQLSTATE('c','0','0','0','2')

/* Class c1 - Environment Exception */
#define ERRCODE_OUT_OF_MEMORY MAKE_SQLSTATE('c','1','0','0','0')

/* Class c2 - File Exception */
#define ERRCODE_OPEN_FILE_FAILURE MAKE_SQLSTATE('c','3','0','0','0')
#define ERRCODE_READ_FILE_FAILURE MAKE_SQLSTATE('c','3','0','0','1')
#define ERRCODE_CONFIG_FILE_FAILURE MAKE_SQLSTATE('c','3','0','0','2')

/* Class c3 - Parameter Exception */
#define ERRCODE_PARAMETER_FAILURE MAKE_SQLSTATE('c','3','0','0','0')
#define ERRCODE_ENVIRONMENT_VARIABLE_FAILURE MAKE_SQLSTATE('c','3','0','0','1')

/* Class c4 - Etcd Exception */
#define ERRCODE_ETCD_OPEN_FAILURE MAKE_SQLSTATE('c','4','0','0','0')

/* Class c5 - Internal Exception */
#define ERRCODE_INTERNAL_ERROR MAKE_SQLSTATE('c','5','0','0','0')
