/*-------------------------------------------------------------------------
 *
 * kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef KWLIST_D_H
#define KWLIST_D_H

#include "parser/kwlookup.h"

static const char ScanKeywords_kw_string[] =
	"abort\0"
	"absolute\0"
	"access\0"
	"account\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"algorithm\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"app\0"
	"append\0"
	"archive\0"
	"array\0"
	"as\0"
	"asc\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"attribute\0"
	"audit\0"
	"authid\0"
	"authorization\0"
	"auto_increment\0"
	"autoextend\0"
	"automapped\0"
	"backward\0"
	"barrier\0"
	"before\0"
	"begin\0"
	"begin_non_anoyblock\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_integer\0"
	"bit\0"
	"blanks\0"
	"blob\0"
	"blockchain\0"
	"body\0"
	"boolean\0"
	"both\0"
	"bucketcnt\0"
	"buckets\0"
	"by\0"
	"byteawithoutorder\0"
	"byteawithoutorderwithequal\0"
	"cache\0"
	"call\0"
	"called\0"
	"cancelable\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"change\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"characterset\0"
	"charset\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"clean\0"
	"client\0"
	"client_master_key\0"
	"client_master_keys\0"
	"clob\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"column_encryption_key\0"
	"column_encryption_keys\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compact\0"
	"compatible_illegal_chars\0"
	"complete\0"
	"completion\0"
	"compress\0"
	"concurrently\0"
	"condition\0"
	"configuration\0"
	"connect\0"
	"connection\0"
	"constant\0"
	"constraint\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"contview\0"
	"conversion\0"
	"convert\0"
	"coordinator\0"
	"coordinators\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csn\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"datafile\0"
	"datanode\0"
	"datanodes\0"
	"datatype_cl\0"
	"date\0"
	"date_format\0"
	"day\0"
	"dbcompatibility\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"delta\0"
	"deltamerge\0"
	"desc\0"
	"deterministic\0"
	"dictionary\0"
	"direct\0"
	"directory\0"
	"disable\0"
	"discard\0"
	"disconnect\0"
	"distinct\0"
	"distribute\0"
	"distribution\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"dumpfile\0"
	"duplicate\0"
	"each\0"
	"elastic\0"
	"else\0"
	"enable\0"
	"enclosed\0"
	"encoding\0"
	"encrypted\0"
	"encrypted_value\0"
	"encryption\0"
	"encryption_type\0"
	"end\0"
	"ends\0"
	"enforced\0"
	"enum\0"
	"eol\0"
	"errors\0"
	"escape\0"
	"escaped\0"
	"escaping\0"
	"event\0"
	"events\0"
	"every\0"
	"except\0"
	"exchange\0"
	"exclude\0"
	"excluded\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"expired\0"
	"explain\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fast\0"
	"features\0"
	"fenced\0"
	"fetch\0"
	"fields\0"
	"fileheader\0"
	"fill_missing_fields\0"
	"filler\0"
	"filter\0"
	"first\0"
	"fixed\0"
	"float\0"
	"following\0"
	"follows\0"
	"for\0"
	"force\0"
	"foreign\0"
	"formatter\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groupparent\0"
	"handler\0"
	"having\0"
	"hdfsdirectory\0"
	"header\0"
	"hold\0"
	"hour\0"
	"identified\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ignore_extra_data\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"incremental\0"
	"index\0"
	"indexes\0"
	"infile\0"
	"inherit\0"
	"inherits\0"
	"initial\0"
	"initially\0"
	"initrans\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"internal\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"ip\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"join\0"
	"key\0"
	"key_path\0"
	"key_store\0"
	"kill\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lc_collate\0"
	"lc_ctype\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"less\0"
	"level\0"
	"like\0"
	"limit\0"
	"lines\0"
	"list\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"log\0"
	"logging\0"
	"login_any\0"
	"login_failure\0"
	"login_success\0"
	"logout\0"
	"loop\0"
	"mapping\0"
	"masking\0"
	"master\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxextents\0"
	"maxsize\0"
	"maxtrans\0"
	"maxvalue\0"
	"merge\0"
	"minextents\0"
	"minus\0"
	"minute\0"
	"minvalue\0"
	"mode\0"
	"model\0"
	"modify\0"
	"month\0"
	"move\0"
	"movement\0"
	"name\0"
	"names\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"next\0"
	"no\0"
	"nocompress\0"
	"nocycle\0"
	"node\0"
	"nologging\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"none\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullcols\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"numstr\0"
	"nvarchar\0"
	"nvarchar2\0"
	"nvl\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"on\0"
	"only\0"
	"operator\0"
	"optimization\0"
	"option\0"
	"optionally\0"
	"options\0"
	"or\0"
	"order\0"
	"out\0"
	"outer\0"
	"outfile\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"owned\0"
	"owner\0"
	"package\0"
	"packages\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"pctfree\0"
	"per\0"
	"percent\0"
	"performance\0"
	"perm\0"
	"placing\0"
	"plan\0"
	"plans\0"
	"policy\0"
	"pool\0"
	"position\0"
	"precedes\0"
	"preceding\0"
	"precision\0"
	"predict\0"
	"preferred\0"
	"prefix\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"priorer\0"
	"private\0"
	"privilege\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"profile\0"
	"publication\0"
	"publish\0"
	"purge\0"
	"query\0"
	"quote\0"
	"randomized\0"
	"range\0"
	"ratio\0"
	"raw\0"
	"read\0"
	"real\0"
	"reassign\0"
	"rebuild\0"
	"recheck\0"
	"recursive\0"
	"recyclebin\0"
	"redisanyvalue\0"
	"ref\0"
	"references\0"
	"refresh\0"
	"reindex\0"
	"reject\0"
	"relative\0"
	"release\0"
	"reloptions\0"
	"remote\0"
	"remove\0"
	"rename\0"
	"repeat\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"resize\0"
	"resource\0"
	"restart\0"
	"restrict\0"
	"return\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"roles\0"
	"rollback\0"
	"rollup\0"
	"rotation\0"
	"row\0"
	"rownum\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"sample\0"
	"savepoint\0"
	"schedule\0"
	"schema\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"separator\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"shippable\0"
	"show\0"
	"shrink\0"
	"shutdown\0"
	"siblings\0"
	"similar\0"
	"simple\0"
	"size\0"
	"skip\0"
	"slave\0"
	"slice\0"
	"smalldatetime\0"
	"smalldatetime_format\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"source\0"
	"space\0"
	"spill\0"
	"split\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"starting\0"
	"starts\0"
	"statement\0"
	"statement_id\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"store\0"
	"stored\0"
	"stratify\0"
	"stream\0"
	"strict\0"
	"strip\0"
	"subpartition\0"
	"subpartitions\0"
	"subscription\0"
	"substring\0"
	"symmetric\0"
	"synonym\0"
	"sys_refcursor\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"target\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"terminated\0"
	"text\0"
	"than\0"
	"then\0"
	"time\0"
	"time_format\0"
	"timecapsule\0"
	"timestamp\0"
	"timestamp_format\0"
	"timestampdiff\0"
	"tinyint\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"tsfield\0"
	"tstag\0"
	"tstime\0"
	"type\0"
	"types\0"
	"unbounded\0"
	"uncommitted\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlimited\0"
	"unlisten\0"
	"unlock\0"
	"unlogged\0"
	"until\0"
	"unusable\0"
	"update\0"
	"use\0"
	"useeof\0"
	"user\0"
	"using\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validation\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variables\0"
	"variadic\0"
	"varying\0"
	"vcgroup\0"
	"verbose\0"
	"verify\0"
	"version\0"
	"view\0"
	"visible\0"
	"volatile\0"
	"wait\0"
	"warnings\0"
	"weak\0"
	"when\0"
	"where\0"
	"while\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"workload\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"year\0"
	"yes\0"
	"zone";

static const uint16 ScanKeywords_kw_offsets[] = {
	0,
	6,
	15,
	22,
	30,
	37,
	41,
	47,
	53,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	123,
	130,
	138,
	144,
	147,
	151,
	161,
	172,
	183,
	186,
	196,
	202,
	209,
	223,
	238,
	249,
	260,
	269,
	277,
	284,
	290,
	310,
	318,
	325,
	332,
	346,
	361,
	365,
	372,
	377,
	388,
	393,
	401,
	406,
	416,
	424,
	427,
	445,
	472,
	478,
	483,
	490,
	501,
	509,
	518,
	523,
	528,
	536,
	542,
	549,
	554,
	564,
	580,
	593,
	601,
	607,
	618,
	624,
	630,
	637,
	655,
	674,
	679,
	685,
	693,
	702,
	710,
	720,
	727,
	749,
	772,
	780,
	788,
	797,
	804,
	814,
	822,
	847,
	856,
	867,
	876,
	889,
	899,
	913,
	921,
	932,
	941,
	952,
	964,
	972,
	981,
	990,
	1001,
	1009,
	1021,
	1034,
	1039,
	1044,
	1051,
	1057,
	1061,
	1065,
	1070,
	1078,
	1094,
	1107,
	1120,
	1135,
	1148,
	1166,
	1179,
	1186,
	1192,
	1197,
	1206,
	1215,
	1224,
	1234,
	1246,
	1251,
	1263,
	1267,
	1283,
	1294,
	1298,
	1306,
	1314,
	1321,
	1329,
	1338,
	1349,
	1358,
	1366,
	1373,
	1383,
	1394,
	1400,
	1411,
	1416,
	1430,
	1441,
	1448,
	1458,
	1466,
	1474,
	1485,
	1494,
	1505,
	1518,
	1521,
	1530,
	1537,
	1544,
	1549,
	1558,
	1568,
	1573,
	1581,
	1586,
	1593,
	1602,
	1611,
	1621,
	1637,
	1648,
	1664,
	1668,
	1673,
	1682,
	1687,
	1691,
	1698,
	1705,
	1713,
	1722,
	1728,
	1735,
	1741,
	1748,
	1757,
	1765,
	1774,
	1784,
	1794,
	1802,
	1809,
	1817,
	1825,
	1835,
	1844,
	1852,
	1858,
	1865,
	1870,
	1879,
	1886,
	1892,
	1899,
	1910,
	1930,
	1937,
	1944,
	1950,
	1956,
	1962,
	1972,
	1980,
	1984,
	1990,
	1998,
	2008,
	2016,
	2023,
	2028,
	2033,
	2042,
	2052,
	2062,
	2069,
	2075,
	2083,
	2092,
	2098,
	2107,
	2119,
	2127,
	2134,
	2148,
	2155,
	2160,
	2165,
	2176,
	2185,
	2188,
	2195,
	2213,
	2219,
	2229,
	2239,
	2248,
	2251,
	2259,
	2269,
	2279,
	2291,
	2297,
	2305,
	2312,
	2320,
	2329,
	2337,
	2347,
	2356,
	2363,
	2369,
	2375,
	2381,
	2393,
	2400,
	2408,
	2412,
	2420,
	2429,
	2439,
	2448,
	2453,
	2463,
	2471,
	2474,
	2477,
	2484,
	2494,
	2499,
	2503,
	2512,
	2522,
	2527,
	2533,
	2542,
	2548,
	2553,
	2564,
	2573,
	2581,
	2591,
	2597,
	2602,
	2607,
	2613,
	2618,
	2624,
	2630,
	2635,
	2642,
	2647,
	2653,
	2663,
	2678,
	2687,
	2692,
	2699,
	2703,
	2711,
	2721,
	2735,
	2749,
	2756,
	2761,
	2769,
	2777,
	2784,
	2790,
	2798,
	2811,
	2822,
	2830,
	2839,
	2848,
	2854,
	2865,
	2871,
	2878,
	2887,
	2892,
	2898,
	2905,
	2911,
	2916,
	2925,
	2930,
	2936,
	2945,
	2953,
	2959,
	2964,
	2967,
	2978,
	2986,
	2991,
	3001,
	3012,
	3023,
	3028,
	3032,
	3040,
	3047,
	3055,
	3062,
	3067,
	3076,
	3083,
	3089,
	3096,
	3104,
	3111,
	3120,
	3130,
	3134,
	3141,
	3144,
	3148,
	3155,
	3160,
	3163,
	3168,
	3177,
	3190,
	3197,
	3208,
	3216,
	3219,
	3225,
	3229,
	3235,
	3243,
	3248,
	3257,
	3265,
	3271,
	3277,
	3285,
	3294,
	3301,
	3309,
	3319,
	3330,
	3338,
	3347,
	3355,
	3359,
	3367,
	3379,
	3384,
	3392,
	3397,
	3403,
	3410,
	3415,
	3424,
	3433,
	3443,
	3453,
	3461,
	3471,
	3478,
	3486,
	3495,
	3504,
	3512,
	3518,
	3526,
	3534,
	3544,
	3555,
	3566,
	3576,
	3584,
	3596,
	3604,
	3610,
	3616,
	3622,
	3633,
	3639,
	3645,
	3649,
	3654,
	3659,
	3668,
	3676,
	3684,
	3694,
	3705,
	3719,
	3723,
	3734,
	3742,
	3750,
	3757,
	3766,
	3774,
	3785,
	3792,
	3799,
	3806,
	3813,
	3824,
	3832,
	3840,
	3846,
	3853,
	3862,
	3870,
	3879,
	3886,
	3896,
	3904,
	3910,
	3917,
	3923,
	3928,
	3934,
	3943,
	3950,
	3959,
	3963,
	3970,
	3975,
	3983,
	3988,
	3995,
	4005,
	4014,
	4021,
	4028,
	4035,
	4042,
	4051,
	4058,
	4068,
	4077,
	4087,
	4100,
	4107,
	4115,
	4128,
	4132,
	4138,
	4143,
	4149,
	4159,
	4164,
	4171,
	4180,
	4189,
	4197,
	4204,
	4209,
	4214,
	4220,
	4226,
	4240,
	4261,
	4270,
	4279,
	4284,
	4291,
	4297,
	4303,
	4309,
	4316,
	4327,
	4333,
	4342,
	4349,
	4359,
	4372,
	4383,
	4389,
	4396,
	4404,
	4410,
	4417,
	4426,
	4433,
	4440,
	4446,
	4459,
	4473,
	4486,
	4496,
	4506,
	4514,
	4528,
	4536,
	4542,
	4549,
	4555,
	4562,
	4574,
	4585,
	4592,
	4597,
	4606,
	4616,
	4627,
	4632,
	4637,
	4642,
	4647,
	4659,
	4671,
	4681,
	4698,
	4712,
	4720,
	4723,
	4732,
	4744,
	4754,
	4760,
	4768,
	4773,
	4778,
	4787,
	4795,
	4803,
	4809,
	4816,
	4821,
	4827,
	4837,
	4849,
	4861,
	4867,
	4874,
	4882,
	4892,
	4901,
	4908,
	4917,
	4923,
	4932,
	4939,
	4943,
	4950,
	4955,
	4961,
	4968,
	4974,
	4983,
	4994,
	5004,
	5010,
	5017,
	5025,
	5034,
	5044,
	5053,
	5061,
	5069,
	5077,
	5084,
	5092,
	5097,
	5105,
	5114,
	5119,
	5128,
	5133,
	5138,
	5144,
	5150,
	5161,
	5168,
	5173,
	5180,
	5188,
	5193,
	5202,
	5210,
	5216,
	5220,
	5234,
	5244,
	5255,
	5265,
	5275,
	5284,
	5290,
	5298,
	5311,
	5316,
	5320,
};

#define SCANKEYWORDS_NUM_KEYWORDS 653

static int
ScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1307] = {
		333,   32767, 32767, -675,  32767, 32767, 0,     32767,
		32767, -497,  32767, 32767, 32767, -27,   680,   32767,
		159,   32767, -54,   181,   32767, -139,  27,    -699,
		0,     32767, 0,     32767, 32767, 32767, 325,   0,
		24,    -573,  32767, 32767, 32767, 967,   -1707, 32767,
		32767, -1775, -88,   618,   32767, 1070,  257,   -261,
		32767, 32767, 32767, 775,   32767, 215,   342,   644,
		919,   800,   32767, 0,     182,   0,     757,   -91,
		32767, 1083,  32767, 524,   32767, 1171,  32767, 289,
		416,   1404,  -199,  -966,  -131,  32767, 32767, 337,
		32767, -674,  32767, 157,   32767, 32767, 32767, -795,
		-2186, -437,  0,     32767, 32767, 32767, -1159, 0,
		1088,  32767, 563,   587,   0,     32767, 32767, 32767,
		-504,  908,   0,     548,   32767, 32767, 32767, 32767,
		32767, -183,  -610,  1,     32767, -708,  0,     32767,
		32767, 0,     -728,  195,   32767, -350,  32767, 32767,
		32767, 0,     12,    32767, 559,   32767, 488,   0,
		1152,  32767, 237,   32767, 508,   32767, -1116, 214,
		795,   32767, 191,   -1371, 0,     1206,  -77,   528,
		0,     32767, 32767, 117,   477,   32767, -358,  -31,
		0,     405,   222,   -174,  32767, 0,     32767, 0,
		32767, 0,     32767, 32767, 32767, 32767, -1483, 32767,
		0,     32767, 935,   32767, 1623,  -135,  32767, 1559,
		32767, 32767, 32767, -45,   1523,  32767, 277,   0,
		247,   32767, -6,    32767, 32767, -297,  319,   93,
		0,     32767, 1006,  519,   -268,  32767, -439,  536,
		18,    467,   0,     0,     27,    82,    32767, -289,
		57,    32767, 38,    111,   32767, 32767, 1427,  160,
		32767, -255,  32767, 32767, 1122,  32767, 123,   0,
		264,   32767, 32767, 32767, 2,     608,   598,   32767,
		212,   0,     32767, 205,   -360,  88,    328,   32767,
		0,     32767, -150,  350,   14,    820,   164,   41,
		-1394, 312,   32767, 32767, 32767, -391,  32767, -593,
		32767, 0,     0,     32767, -263,  320,   0,     659,
		-735,  32767, 32767, 32767, -207,  32767, 1926,  32767,
		0,     461,   0,     402,   32767, 32767, 32767, 551,
		204,   43,    0,     499,   32767, 32767, 262,   32767,
		417,   126,   229,   -38,   32767, 315,   32767, 32767,
		2014,  32767, -57,   -431,  554,   -531,  32767, 32767,
		128,   1137,  0,     32767, 32767, 650,   32767, 32767,
		32767, 0,     1254,  32767, 3,     0,     32767, 32767,
		547,   32767, 50,    137,   32767, 32767, 0,     532,
		190,   32767, 32767, 523,   1286,  -164,  316,   32767,
		-20,   32767, 32767, 32767, 598,   62,    32767, 0,
		642,   32767, 32767, 819,   1183,  32767, 32767, 0,
		568,   32767, 32767, 0,     32767, 213,   -416,  2057,
		-352,  32767, 32767, 32767, -451,  32767, 0,     32767,
		32767, 541,   24,    32767, -435,  32767, 395,   32767,
		32767, 452,   569,   -201,  204,   0,     2233,  32767,
		495,   227,   115,   208,   0,     193,   32767, 32767,
		32767, 32767, 32767, -467,  449,   32767, 32767, 198,
		32767, 405,   0,     0,     75,    0,     32767, -405,
		-569,  32767, 32767, 32767, 32767, 32767, 43,    0,
		32767, -2270, 191,   570,   32767, -64,   -1152, 32767,
		328,   119,   32767, 0,     32767, 32767, 385,   0,
		32767, -108,  1081,  32767, -9,    356,   0,     339,
		215,   1301,  32767, -1727, 124,   32767, 1906,  245,
		32767, 173,   186,   32767, 245,   32767, 32767, 32767,
		32767, 482,   517,   -1718, 0,     448,   32767, 32767,
		0,     831,   -88,   32767, 32767, -1700, 497,   1743,
		32767, 0,     32767, 0,     1529,  32767, 491,   32767,
		32767, 555,   32767, 0,     147,   32767, 1098,  522,
		639,   311,   32767, 0,     32767, 58,    32767, 634,
		32767, 32767, -276,  326,   22,    0,     32767, 32767,
		-612,  32767, 32767, 0,     32767, 348,   566,   32767,
		-1182, 0,     32767, 0,     -136,  280,   109,   317,
		32767, 41,    32767, 32767, 83,    432,   0,     -927,
		32767, 32767, 0,     32767, 48,    179,   32767, 1190,
		32767, 142,   0,     304,   789,   136,   443,   351,
		114,   578,   148,   0,     32767, -446,  193,   437,
		32767, 0,     32767, 32767, 0,     32767, 32767, -378,
		397,   0,     32767, 32767, -193,  151,   1204,  32767,
		0,     130,   231,   131,   571,   557,   274,   137,
		210,   32767, 32767, 32767, -218,  34,    231,   289,
		246,   0,     -16,   423,   0,     -1367, 0,     -105,
		128,   0,     0,     389,   0,     243,   0,     460,
		693,   247,   -509,  32767, -252,  301,   1392,  32767,
		32767, 32767, 90,    -572,  740,   507,   32767, 32767,
		1616,  0,     262,   32767, 351,   2625,  527,   263,
		32767, 138,   32767, 107,   32767, 32767, -361,  0,
		336,   32767, 32767, 0,     32767, 177,   8,     -350,
		111,   32767, 567,   0,     1749,  32767, 32767, 32767,
		32767, 709,   32767, 380,   32767, 32767, 32767, -699,
		217,   -677,  32767, 32767, 36,    0,     32767, 32767,
		58,    -388,  1426,  32767, -297,  32767, 32767, 1312,
		-74,   0,     -534,  32767, 32767, 32767, 32767, 32767,
		32767, -2300, 32767, 32767, 90,    580,   1009,  492,
		621,   0,     284,   32767, 32767, 175,   315,   -939,
		32767, 123,   32767, 32767, 32767, 165,   32767, 0,
		689,   32767, 104,   341,   32767, 1035,  -740,  32767,
		945,   32767, -919,  -564,  407,   -155,  32767, 3,
		32767, 834,   32767, -97,   -117,  32767, -105,  32767,
		-343,  32767, -1340, 197,   32767, 32767, 32767, 0,
		15,    32767, 20,    249,   32767, 55,    610,   258,
		32767, 0,     0,     360,   1397,  3,     0,     32767,
		32767, 32767, 513,   652,   -105,  32767, 398,   426,
		41,    0,     -747,  403,   32767, -810,  32767, 32767,
		32767, 32767, 318,   32767, 32767, 338,   32767, -308,
		484,   1538,  0,     13,    32767, 374,   32767, 32767,
		32767, 515,   -770,  32767, 32767, 286,   101,   99,
		0,     32767, 0,     32767, 1041,  554,   5,     481,
		161,   -1471, 73,    32767, -656,  32767, 582,   32767,
		-306,  32767, 280,   32767, 32767, 0,     -684,  2067,
		32767, 32767, 88,    32767, 32767, 32767, 740,   -202,
		32767, 32767, 32767, 149,   197,   856,   32767, 32767,
		0,     -256,  587,   0,     32767, 32767, -232,  32767,
		-1475, -167,  -1054, 32767, 0,     393,   0,     0,
		32767, -889,  32767, 125,   32767, 32767, 32767, 420,
		32,    614,   66,    32767, 32767, 677,   527,   218,
		32767, 32767, -323,  984,   0,     -790,  32767, 631,
		-773,  279,   28,    358,   0,     32767, -104,  199,
		0,     324,   107,   1250,  241,   32767, 561,   -69,
		32767, 0,     32767, 2803,  920,   -431,  -899,  -851,
		32767, 32767, 798,   229,   32767, 0,     32767, 543,
		32767, 32767, 32767, 471,   70,    413,   32767, 3,
		-76,   32767, 32767, 255,   -2178, 235,   32767, -896,
		-322,  1176,  32767, 32767, 297,   32767, 124,   -413,
		32767, 0,     -235,  32767, 145,   -1093, 32767, 25,
		154,   32767, 207,   251,   32767, 32767, 32767, 203,
		32767, 2508,  32767, 0,     -1297, 286,   0,     590,
		-1110, 359,   32767, 2328,  32767, 0,     32767, 32767,
		-50,   113,   32767, 0,     745,   361,   0,     251,
		-744,  32767, 1534,  32767, 586,   -216,  32767, 32767,
		0,     -268,  32767, -745,  8,     -149,  638,   32767,
		32767, 32767, 77,    452,   169,   -195,  0,     -1326,
		32767, 32767, 32767, 205,   32767, 0,     0,     0,
		-938,  472,   32767, 32767, 0,     1341,  537,   32767,
		32767, 32767, 0,     -286,  152,   907,   0,     507,
		0,     1030,  166,   32767, 32767, 148,   0,     -881,
		34,    32767, 32767, 0,     32767, 32767, 595,   270,
		0,     0,     451,   421,   -425,  -201,  32767, 32767,
		465,   35,    32767, 32767, 246,   32767, 32767, 32767,
		93,    0,     32767, 196,   862,   32767, 32767, 32767,
		64,    244,   32767, 570,   32767, -434,  0,     559,
		32767, 645,   0,     32767, 32767, 32767, -41,   421,
		158,   1029,  -498,  165,   0,     254,   0,     622,
		-61,   0,     0,     473,   -731,  152,   1123,  548,
		166,   0,     32767, 32767, 211,   411,   -986,  32767,
		32767, 1743,  407,   1134,  32767, 32767, 32767, -795,
		0,     924,   228,   0,     32767, 32767, 32767, 127,
		427,   32767, 0,     0,     607,   0,     32767, 32767,
		32767, 1097,  -184,  32767, 32767, 1003,  32767, 0,
		-1904, 32767, 0,     32767, 265,   -830,  278,   0,
		1346,  32767, 32767, 32767, -386,  32767, 32767, 0,
		514,   -586,  370,   903,   1093,  -270,  -206,  0,
		592,   106,   32767, 279,   0,     -603,  32767, 0,
		32767, 422,   470,   32767, -447,  0,     32767, 518,
		586,   -158,  0,     0,     0,     598,   -799,  577,
		32767, 0,     32767, 0,     -424,  0,     381,   32767,
		32767, 527,   1481,  32767, 32767, 32767, -112,  -758,
		398,   0,     2509,  371,   32767, 1689,  509,   0,
		372,   1058,  0,     32767, 248,   32767, 32767, 21,
		787,   0,     32767, 32767, 32767, 511,   -120,  0,
		32767, 293,   0,     807,   992,   242,   0,     52,
		425,   112,   32767, -308,  256,   626,   -553,  30,
		0,     32767, -561,  0,     146,   32767, 0,     32767,
		0,     1040,  32767, 32767, 521,   514,   32767, 0,
		-10,   287,   32767, 143,   32767, 0,     1404,  240,
		486,   32767, 99,    32767, -1183, -1006, -799,  0,
		32767, 100,   266,   451,   37,    388,   -870,  32767,
		-721,  0,     32767, 32767, 32767, 334,   32767, 0,
		-139,  429,   858,   32767, 132,   0,     0,     32767,
		583,   32767, 0,     -659,  32767, 0,     32767, 32767,
		32767, 0,     450
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 0;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 31 + c;
	}
	return h[a % 1307] + h[b % 1307];
}

const ScanKeywordList ScanKeywords = {
	ScanKeywords_kw_string,
	ScanKeywords_kw_offsets,
	ScanKeywords_hash_func,
	SCANKEYWORDS_NUM_KEYWORDS,
	26
};

#endif							/* KWLIST_D_H */
