/*
 * Copyright (c) 2020 Huawei Technologies Co.,Ltd.
 *
 * openGauss is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 * -------------------------------------------------------------------------
 *
 * config.h
 *    Masstree index configurations template.
 *
 * IDENTIFICATION
 *    src/gausskernel/storage/mot/core/src/storage/index/masstree/config.h
 *
 * -------------------------------------------------------------------------
 */

#include "mot_masstree_config.hpp"

#ifndef MASSTREE_CONFIG_H
#define MASSTREE_CONFIG_H

#define HAVE_CXX_TEMPLATE_ALIAS MOT_HAVE_CXX_TEMPLATE_ALIAS
#define HAVE_INT64_T_IS_LONG MOT_HAVE_INT64_T_IS_LONG
#define HAVE_SIZE_T_IS_UNSIGNED_LONG MOT_HAVE_SIZE_T_IS_UNSIGNED_LONG
#define HAVE_STD_HASH MOT_HAVE_STD_HASH
#define HAVE_STD_IS_TRIVIALLY_COPYABLE MOT_HAVE_STD_IS_TRIVIALLY_COPYABLE
#define HAVE_STD_IS_TRIVIALLY_DESTRUCTIBLE MOT_HAVE_STD_IS_TRIVIALLY_DESTRUCTIBLE
#define HAVE_SUPERPAGE MOT_HAVE_SUPERPAGE
#define HAVE_TYPE_TRAITS MOT_HAVE_TYPE_TRAITS
#define HAVE_UNALIGNED_ACCESS MOT_HAVE_UNALIGNED_ACCESS
#define HAVE___BUILTIN_CLZ MOT_HAVE___BUILTIN_CLZ
#define HAVE___BUILTIN_CLZL MOT_HAVE___BUILTIN_CLZL
#define HAVE___BUILTIN_CLZLL MOT_HAVE___BUILTIN_CLZLL
#define HAVE___BUILTIN_CTZ MOT_HAVE___BUILTIN_CTZ
#define HAVE___BUILTIN_CTZL MOT_HAVE___BUILTIN_CTZL
#define HAVE___BUILTIN_CTZLL MOT_HAVE___BUILTIN_CTZLL
#define HAVE___HAS_TRIVIAL_COPY MOT_HAVE___HAS_TRIVIAL_COPY
#define HAVE___HAS_TRIVIAL_DESTRUCTOR MOT_HAVE___HAS_TRIVIAL_DESTRUCTOR
#define HAVE___SYNC_BOOL_COMPARE_AND_SWAP MOT_HAVE___SYNC_BOOL_COMPARE_AND_SWAP
#define HAVE___SYNC_BOOL_COMPARE_AND_SWAP_8 MOT_HAVE___SYNC_BOOL_COMPARE_AND_SWAP_8
#define HAVE___SYNC_FETCH_AND_ADD MOT_HAVE___SYNC_FETCH_AND_ADD
#define HAVE___SYNC_FETCH_AND_ADD_8 MOT_HAVE___SYNC_FETCH_AND_ADD_8
#define HAVE___SYNC_FETCH_AND_OR MOT_HAVE___SYNC_FETCH_AND_OR
#define HAVE___SYNC_FETCH_AND_OR_8 MOT_HAVE___SYNC_FETCH_AND_OR_8
#define HAVE___SYNC_VAL_COMPARE_AND_SWAP MOT_HAVE___SYNC_VAL_COMPARE_AND_SWAP
#define HAVE___SYNC_VAL_COMPARE_AND_SWAP_8 MOT_HAVE___SYNC_VAL_COMPARE_AND_SWAP_8
#define MASSTREE_MAXKEYLEN MOT_MASSTREE_MAXKEYLEN
#define SIZEOF_INT MOT_SIZEOF_INT
#define SIZEOF_LONG MOT_SIZEOF_LONG
#define SIZEOF_LONG_LONG MOT_SIZEOF_LONG_LONG
#define SIZEOF_SHORT MOT_SIZEOF_SHORT
#define WORDS_BIGENDIAN_SET MOT_WORDS_BIGENDIAN_SET

#endif
