#
# Makefile for the security subsystem
#
# src/gausskernel/security/Makefile
#

subdir = src/gausskernel/security
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = keymanagement iprange gs_policy

include $(top_srcdir)/src/gausskernel/common.mk
