#
# Makefile for the security subsystem
#
# src/gausskernel/security/Makefile
#

subdir = src/gausskernel/security
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = iprange gs_policy gs_ledger tde_key_management

include $(top_srcdir)/src/gausskernel/common.mk
