#-------------------------------------------------------------------------
#
# Makefile for src/common/pl/plpgsql (PostgreSQL's SQL procedural language)
#
# Copyright (c) 1994, Regents of the University of California
#
# src/common/pl/plpgsql/Makefile
#
#-------------------------------------------------------------------------

subdir = src/common/pl/plpgsql
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

all install installdirs uninstall distprep clean distclean maintainer-clean coverage:
	$(MAKE) -C src $@
