#---------------------------------------------------------------------------------------
#
#  IDENTIFICATION
#        src/gausskernel/ddes/Makefile
#
# ---------------------------------------------------------------------------------------

subdir = src/gausskernel/ddes
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = adapter

include $(top_srcdir)/src/gausskernel/common.mk
