#---------------------------------------------------------------------------------------
#
#  IDENTIFICATION
#        src/gausskernel/optimizer/Makefile
#
# ---------------------------------------------------------------------------------------

subdir = src/gausskernel/optimizer
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = geqo path plan prep util rewrite commands

include $(top_srcdir)/src/gausskernel/common.mk
