{
 "title": "DBMind-slow-query-analysis",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Unique Slow Queries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_catalog.count(1) FROM (SELECT distinct schema_name, db_name, query FROM tb_slow_queries);"
    }
   ]
  },
  {
   "title": "Slow Query Threshold",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT setting::bigint as threshold FROM pg_settings WHERE name = 'log_min_duration_statement';"
    }
   ]
  },
  {
   "title": "Mean Duration for Slow Query",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select pg_catalog.avg(duration_time) from tb_slow_queries;"
    }
   ]
  },
  {
   "title": "Statistics For Database",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT db_name, pg_catalog.count(1) FROM tb_slow_queries GROUP BY db_name;"
    }
   ]
  },
  {
   "title": "Statistics For Schema",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT schema_name, pg_catalog.count(1) FROM tb_slow_queries GROUP BY schema_name;"
    }
   ]
  },
  {
   "title": "System Table Rate In Slow Queries",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select pg_catalog.count(1) from tb_slow_queries where query like '%pg\\_%') as system_table, (select pg_catalog.count(1) from tb_slow_queries) - system_table as bussiness_table;"
    }
   ]
  },
  {
   "title": "Distribution of Slow Query",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select pg_catalog.count(1) from tb_slow_queries where query like '%select%') as SELECT, (select pg_catalog.count(1) from tb_slow_queries where query like '%delete%') as DELETE, (select pg_catalog.count(1) from tb_slow_queries where query like '%insert%') as INSERT, (select pg_catalog.count(1) from tb_slow_queries where query like '%update%') as UPDATE;\n"
    }
   ]
  },
  {
   "title": "Statistics for Root Cause",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 14, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH t_causes AS (SELECT trim(pg_catalog.split_part(pg_catalog.split_part(cause, ':', '2'), ',', '2')) AS title,\r\n                         trim(pg_catalog.split_part(pg_catalog.split_part(cause, ':', '2'), ',', '1'))::float AS prob\r\n   FROM\r\n     (SELECT pg_catalog.unnest(pg_catalog.regexp_split_to_array(root_cause, '\\n')) AS cause\r\n      FROM tb_slow_queries))\r\nSELECT title,\r\n       pg_catalog.sum(prob)\r\nFROM\r\n  t_causes\r\nGROUP BY title \r\nhaving title is not null;"
    }
   ]
  },
  {
   "title": "Mean CPU Time ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (pg_catalog.avg(cpu_time) / 1000 / 1000) FROM tb_slow_queries;\n"
    }
   ]
  },
  {
   "title": "Mean IO Time ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (pg_catalog.avg(data_io_time) / 1000 / 1000) FROM tb_slow_queries;\n"
    }
   ]
  },
  {
   "title": "Mean Buffer Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (pg_catalog.avg(hit_rate) * 100) FROM tb_slow_queries;\n"
    }
   ]
  },
  {
   "title": "Mean Fetch Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (pg_catalog.avg(fetch_rate) * 100) FROM tb_slow_queries;\n"
    }
   ]
  },
  {
   "title": "Slow Query Trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select (start_at / 1000)::bigint as time, pg_catalog.count(1) from tb_slow_queries group by time order by time;\n"
    }
   ]
  },
  {
   "title": "Statistics for Slow Query Template (template_id)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select template_id::text, pg_catalog.count(1) from tb_slow_queries group by template_id;"
    }
   ]
  },
  {
   "title": "Slow Query Templates",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "rawSql": "select distinct t1.template_id, t1.count, t2.query from (select template_id, pg_catalog.count(1) as count from tb_slow_queries group by template_id) t1 inner join tb_slow_queries t2 on t1.template_id = t2.template_id order by t1.count desc;"
    }
   ]
  },
  {
   "title": "Slow Query Statistics",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT db_name, query, root_cause, suggestion, pg_catalog.count(query) FROM tb_slow_queries GROUP BY db_name, query, root_cause, suggestion;\n"
    }
   ]
  },
  {
   "title": "Recent 50 Slow Queries",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "select * from tb_slow_queries order by start_at desc limit 50;"
    }
   ]
  }
 ]
}