FROM ubuntu:24.04

ARG VERSION=7.0.0

COPY openGauss-Server-${VERSION}-openEuler24.03-x86_64.tar.bz2 .
COPY gosu-amd64 /usr/local/bin/gosu
# remove all lines containing scws if do no want to chparser#
COPY scws.tar.gz .

ENV LANG en_US.utf8

RUN set -eux; \
    apt-get update && \
    apt-get install -y bzip2 curl libaio-dev passwd tar libjemalloc-dev libcgroup-dev libcurl4-openssl-dev liblapacke libedit-dev libxml2-dev liblz4-dev libnuma-dev unixodbc-dev libssl-dev zstd openjdk-11-jdk wget unzip libopenblas-dev locales && \
    groupadd -g 70 omm && \
    useradd -u 70 -g omm -m -d /home/omm omm && \
    mkdir -p /var/lib/opengauss && \
    mkdir -p /usr/local/opengauss && \
    mkdir -p /var/run/opengauss  && \
    mkdir /docker-entrypoint-initdb.d && \
    tar -jxf openGauss-Server-${VERSION}-openEuler24.03-x86_64.tar.bz2 -C /usr/local/opengauss && \
    chown -R omm:omm /var/run/opengauss && chown -R omm:omm /usr/local/opengauss && chown -R omm:omm /var/lib/opengauss &&  chown -R omm:omm /docker-entrypoint-initdb.d && \
    chmod 2777 /var/run/opengauss && \
    rm -rf openGauss-Server-${VERSION}-openEuler24.03-x86_64.tar.bz2 && \
    tar -xzvf scws.tar.gz; chown -R omm:omm /scws; rm -rf scws.tar.gz && \
    chmod 1777 /tmp && \
	ln -s  /usr/lib/x86_64-linux-gnu/libaio.so /usr/lib/x86_64-linux-gnu/libaio.so.1 && \
	ln -s /usr/lib/x86_64-linux-gnu/libedit.so.2 /usr/lib/x86_64-linux-gnu/libedit.so.0 && \
	cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/local/opengauss/lib/libstdc++.so.6 && \
	localedef -i en_US -c -f UTF-8 en_US.UTF-8 && \
	apt-get clean

RUN set -eux; \
    echo "export GAUSSHOME=/usr/local/opengauss"  >> /home/omm/.bashrc && \
    echo "export PATH=\$GAUSSHOME/bin:\$PATH " >> /home/omm/.bashrc && \
    echo "export LD_LIBRARY_PATH=\$GAUSSHOME/lib:\$LD_LIBRARY_PATH" >> /home/omm/.bashrc && \
	echo "export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/liblapacke.so.3" >> /home/omm/.bashrc && \
	echo "export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/liblapacke.so.3" >> /etc/profile

RUN set -eux; echo "export TMOUT=0 >> /etc/bashrc"

ENV GOSU_VERSION 1.12
RUN set -eux; \
     chmod +x /usr/local/bin/gosu

ENV PGDATA /var/lib/opengauss/data

COPY entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh;ln -s /usr/local/bin/entrypoint.sh / # backwards compat

ENTRYPOINT ["entrypoint.sh"]

EXPOSE 5432
CMD ["gaussdb"]
