set current_schema='shipping_schema';
drop table shipping_test_row;
drop table shipping_test_col;
drop table t1;
drop table t2;
drop table t3;
drop table t4;
drop table t5;
drop table t6;
drop table t7;
drop table t8;
drop table t9;
drop view view_t10;
drop table t10;
drop table t11;
drop table t12;
drop table t13;
drop table t14;
drop table t15;
drop table ship_t1;
drop table ship_t2;
drop table ship_t4;
drop table ship_t5;
drop data source ecshipping;
drop table shipping_insert;
drop table shipping_test_replicalte;
drop table seq_t1;
drop table seq_t2;
drop table seq_t3;
drop sequence seq1;
drop schema shipping_schema;
drop node group ship_ng0;
