# Copyright (c) 2020 Huawei Technologies Co.,Ltd.
#
# openGauss is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
C1 = 'LOCK_CONTENTION_SQL'
C2 = 'LARGE_DEAD_RATE'
C3 = 'LARGE_FETCHED_TUPLES'
C4 = 'LARGE_RETURNED_ROWS'
C5 = 'SMALL_SHARED_BUFFER_SQL'
C6 = 'UPDATED_REDUNDANT_INDEX'
C7 = 'LARGE_UPDATED_TUPLES'
C8 = 'INSERTED_REDUNDANT_INDEX'
C9 = 'INSERTED_INDEX_NUMBER'
C10 = 'LARGE_INSERTED_TUPLES'
C11 = 'DELETED_REDUNDANT_INDEX'
C12 = 'LARGE_DELETED_TUPLES'
C13 = 'EXTERNAL_SORT'
C14 = 'LARGE_TPS'
C15 = 'VACUUM_SQL'
C16 = 'ANALYZE_SQL'
C17 = 'SYSTEM_SQL'
C_UNKNOWN = 'UNKNOWN'
C_VIEW = 'DATABASE_VIEW'
C_SQL = 'ILLEGAL_SQL'
