# Copyright (c) 2020 Huawei Technologies Co.,Ltd.
#
# openGauss is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
C1 = 'LOCK_CONTENTION_SQL'
C2 = 'LARGE_DEAD_RATE'
C3 = 'LARGE_FETCHED_TUPLES'
C4 = 'SMALL_SHARED_BUFFER_SQL'
C5 = 'UPDATED_REDUNDANT_INDEX'
C6 = 'INSERTED_REDUNDANT_INDEX'
C7 = 'DELETED_REDUNDANT_INDEX'
C8 = 'LARGE_UPDATED_TUPLES'
C9 = 'LARGE_INSERTED_TUPLES'
C10 = 'LARGE_DELETED_TUPLES'
C11 = 'INSERTED_INDEX_NUMBER'
C12 = 'EXTERNAL_SORT'
C13 = 'VACUUM_CONFLICT'
C14 = 'ANALYZE_CONFLICT'
C15 = 'LOAD_CONCENTRATION'
C16 = 'SYSTEM_RESOURCE'
C17 = 'ABNORMAL_THREAD_POOL'
C18 = 'LARGE_CONNECTION_OCCUPY_RATE'
C19 = 'ABNORMAL_WAIT_EVENT'
C20 = 'LACK_STATISTIC_INFO'
C21 = 'LOW_CHECKPOINT_EFFICIENT'
C22 = 'LOW_REPLICATION_EFFICIENT'
C23 = 'ABNORMAL_SEQSCAN_OPERATOR'
C24 = 'ABNORMAL_NESTLOOP_OPERATOR'
C25 = 'ABNORMAL_HASHJOIN_OPERATOR'
C26 = 'ABNORMAL_GROUPAGG_OPERATOR'
C27 = 'ABNORMAL_SQL_STRUCTURE'
C28 = 'TIMED_TASK_CONFLICT'
C29 = 'ABNORMAL_PLAN_TIME'
C_UNKNOWN = 'UNKNOWN'
C_VIEW = 'DATABASE_VIEW'
C_SQL = 'ILLEGAL_SQL'
