\! gs_ktool -d all
\! gs_ktool -g
\! gs_ktool -g

CREATE CLIENT MASTER KEY MyCMK WITH ( KEY_STORE = gs_ktool , KEY_PATH = "gs_ktool/1" , ALGORITHM = AES_256_CBC);
CREATE COLUMN ENCRYPTION KEY MyCEK770 WITH VALUES (CLIENT_MASTER_KEY = MyCMK, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);
CREATE TABLE IF NOT EXISTS tr2(i1 INT ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = MyCEK770, ENCRYPTION_TYPE = DETERMINISTIC) , i2 INT);
\d tr2
DROP COLUMN ENCRYPTION KEY MyCEK770;
DROP CLIENT MASTER KEY MyCMK;
DROP COLUMN ENCRYPTION KEY MyCEK770 CASCADE;
DROP TABLE tr2;
DROP COLUMN ENCRYPTION KEY MyCEK770 CASCADE;
\d tr2
DROP CLIENT MASTER KEY MyCMK;
DROP TABLE tr2;


CREATE CLIENT MASTER KEY MyCMK WITH ( KEY_STORE = gs_ktool , KEY_PATH = "gs_ktool/2" , ALGORITHM = AES_256_CBC);
CREATE CLIENT MASTER KEY MyCMK1 WITH ( KEY_STORE = gs_ktool , KEY_PATH = "gs_ktool/1" , ALGORITHM = AES_256_CBC);

CREATE COLUMN ENCRYPTION KEY MyCEK WITH VALUES (CLIENT_MASTER_KEY = MyCMK1, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256, ENCRYPTED_VALUE='abcdefghieffffffefoewinfewgnwlsdngkaisgndfkaghksngsdngjklmnopqrstuvwxyz1');
CREATE COLUMN ENCRYPTION KEY MyCEK1 WITH VALUES (CLIENT_MASTER_KEY = MyCMK, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);

CREATE COLUMN ENCRYPTION KEY MyCEK2 WITH VALUES (CLIENT_MASTER_KEY = MyCMK,CLIENT_MASTER_KEY = MyCMK1, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);
CREATE COLUMN ENCRYPTION KEY MyCEK3 WITH VALUES (CLIENT_MASTER_KEY = MyCMK,ALGORITHM = RSA_2048, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);
CREATE COLUMN ENCRYPTION KEY MyCEK4 WITH VALUES (CLIENT_MASTER_KEY = MyCMK,ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256,ENCRYPTED_VALUE='abcdefghijklmno',ENCRYPTED_VALUE='abcdefghijklmnopqrstuvwxyz1');

DROP COLUMN ENCRYPTION KEY IF EXISTS MyCEK;
DROP COLUMN ENCRYPTION KEY IF EXISTS MyCEK1;
DROP COLUMN ENCRYPTION KEY IF EXISTS MyCEK2;
DROP COLUMN ENCRYPTION KEY IF EXISTS MyCEK3;
DROP COLUMN ENCRYPTION KEY IF EXISTS MyCEK4;
DROP CLIENT MASTER KEY MyCMK CASCADE;
DROP CLIENT MASTER KEY MyCMK1 CASCADE;

\! gs_ktool -d all