\! gs_ktool -d all
\! gs_ktool -g
\! gs_ktool -g

DROP CLIENT MASTER KEY IF EXISTS MyCMK CASCADE;
DROP CLIENT MASTER KEY testns.MyCMKt CASCADE;
CREATE CLIENT MASTER KEY MyCMK WITH ( KEY_STORE = gs_ktool , KEY_PATH = "gs_ktool/1" , ALGORITHM = AES_256_CBC);
CREATE COLUMN ENCRYPTION KEY MyCEK WITH VALUES (CLIENT_MASTER_KEY = MyCMK, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);
CREATE TABLE tbl2 (b int, c int  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = public.MyCEK, ENCRYPTION_TYPE = DETERMINISTIC), d int  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = public.MyCEK, ENCRYPTION_TYPE = DETERMINISTIC));
CREATE SCHEMA testns;
CREATE CLIENT MASTER KEY testns.MyCMKt WITH ( KEY_STORE = gs_ktool , KEY_PATH = "gs_ktool/2" , ALGORITHM = AES_256_CBC);
CREATE COLUMN ENCRYPTION KEY testns.MyCEK WITH VALUES (CLIENT_MASTER_KEY = testns.MyCMKt, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);
SET search_path to testns;
CREATE COLUMN ENCRYPTION KEY MyCEK2 WITH VALUES (CLIENT_MASTER_KEY = testns.MyCMKt, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);
CREATE COLUMN ENCRYPTION KEY MyCEK3 WITH VALUES (CLIENT_MASTER_KEY = public.MyCMK, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);
CREATE TABLE tbl2 (b int, c int  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = public.MyCEK, ENCRYPTION_TYPE = DETERMINISTIC), d int  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = public.MyCEK, ENCRYPTION_TYPE = DETERMINISTIC));
SET search_path to testns, public;
SELECT d FROM tbl2 WHERE c = 1;
DROP TABLE tbl2;
DROP SCHEMA testns;
DROP SCHEMA testns CASCADE;
DROP TABLE tbl2;
DROP CLIENT MASTER KEY MyCMK CASCADE;

\! gs_ktool -d all
