\! gs_ktool -d all
\! gs_ktool -g

DROP CLIENT MASTER KEY IF EXISTS MyCMK CASCADE;
CREATE CLIENT MASTER KEY MyCMK WITH ( KEY_STORE = gs_ktool , KEY_PATH = "gs_ktool/1" , ALGORITHM = AES_256_CBC);
CREATE COLUMN ENCRYPTION KEY MyCEK770 WITH VALUES (CLIENT_MASTER_KEY = MyCMK, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);

CREATE TABLE IF NOT EXISTS tr2(i1 INT ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = MyCEK770, ENCRYPTION_TYPE = DETERMINISTIC) , i2 INT);
BEGIN;
INSERT INTO tr2 (i1, i2) VALUES (12, 13);
INSERT INTO tr2 VALUES (15,16);
COMMIT;
SELECT * from tr2 ORDER BY i2;
BEGIN;
INSERT INTO tr2 (i1, i2) VALUES (22, 23), (24, 25), (26,27);
INSERT INTO tr2 VALUES (35,36), (36,37), (38,39);
COMMIT;
SELECT * from tr2 ORDER BY i2;

DROP TABLE tr2;

DROP COLUMN ENCRYPTION KEY MyCEK770;
DROP CLIENT MASTER KEY MyCMK;

\! gs_ktool -d all