subdir = src/common/interfaces/ecpg/test/performance
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/$(subdir)/../Makefile.regress

TESTS = perftest perftest.cpp

all: $(TESTS)
