subdir = src/gausskernel/storage/access
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = cbtree common dfs heap index nbtree psort rmgrdesc transam obs hash spgist gist gin hbstore redo table

include $(top_srcdir)/src/gausskernel/common.mk
