subdir = src/common/interfaces/ecpg/test/connect
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/$(subdir)/../Makefile.regress

TESTS = test1 test1.cpp \
        test2 test2.cpp \
        test3 test3.cpp \
        test4 test4.cpp \
        test5 test5.cpp

all: $(TESTS)
