#----------------------------------------------------------------------------
#
# common Makefile
#
# common/Makefile
#
#----------------------------------------------------------------------------

subdir = src/common
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = port  timezone interfaces pgxc 

$(recurse)
