-- test bpchar char semantic cast
SET client_min_messages = warning;
drop table if exists test_bpchar_char;
create table test_bpchar_char (id int, val char (30 char));
insert into test_bpchar_char values (1, 1);
insert into test_bpchar_char values (2, '2'::text);
insert into test_bpchar_char values (3, '3'::clob);
select val::text from test_bpchar_char;
select val::clob from test_bpchar_char;
select val::char(4 byte) from test_bpchar_char;
insert into test_bpchar_char values (4, '4'::char(4 byte));
insert into test_bpchar_char values (5, '5'::nvarchar2);
select val::nvarchar2 from test_bpchar_char;
insert into test_bpchar_char values (6, '66'::char);
insert into test_bpchar_char values (7, '7'::name);
select val::char from test_bpchar_char;
select val::name from test_bpchar_char;
insert into test_bpchar_char values (8, '8'::cidr);
insert into test_bpchar_char values (9, '9.0.0.0'::inet);
insert into test_bpchar_char values (10, 't'::bool);
insert into test_bpchar_char values (11, '11'::xml);
select val::xml from test_bpchar_char;
insert into test_bpchar_char values (20, '20'::int8);
select val::int8 from test_bpchar_char where id = 20;
insert into test_bpchar_char values (21, '2020-1-1 21:00:00'::date);
select val::date from test_bpchar_char where id = 21;
select val::numeric from test_bpchar_char where id = 20;
select val::int4 from test_bpchar_char where id = 20;
select val::timestamp from test_bpchar_char where id = 21;
insert into test_bpchar_char values (22, '22'::int1);
insert into test_bpchar_char values (23, '23'::int2);
insert into test_bpchar_char values (24, '24'::float4);
insert into test_bpchar_char values (25, '25'::float8);
insert into test_bpchar_char values (26, '26'::numeric);
select val from test_bpchar_char;
drop table test_bpchar_char;

-- test bpchar byte semantic cast
drop table if exists test_bpchar_byte;
create table test_bpchar_byte (id int, val char (30 byte));
insert into test_bpchar_byte values (1, 1);
insert into test_bpchar_byte values (2, '2'::text);
insert into test_bpchar_byte values (3, '3'::clob);
select val::text from test_bpchar_byte;
select val::clob from test_bpchar_byte;
select val::char(4 byte) from test_bpchar_byte;
insert into test_bpchar_byte values (4, '4'::char(4 byte));
insert into test_bpchar_byte values (5, '5'::nvarchar2);
select val::nvarchar2 from test_bpchar_byte;
insert into test_bpchar_byte values (6, '66'::char);
insert into test_bpchar_byte values (7, '7'::name);
select val::char from test_bpchar_byte;
select val::name from test_bpchar_byte;
insert into test_bpchar_byte values (8, '8'::cidr);
insert into test_bpchar_byte values (9, '9.0.0.0'::inet);
insert into test_bpchar_byte values (10, 't'::bool);
insert into test_bpchar_byte values (11, '11'::xml);
select val::xml from test_bpchar_byte;
insert into test_bpchar_byte values (20, '20'::int8);
select val::int8 from test_bpchar_byte where id = 20;
insert into test_bpchar_byte values (21, '2020-1-1 21:00:00'::date);
select val::date from test_bpchar_byte where id = 21;
select val::numeric from test_bpchar_byte where id = 20;
select val::int4 from test_bpchar_byte where id = 20;
select val::timestamp from test_bpchar_byte where id = 21;
insert into test_bpchar_byte values (22, '22'::int1);
insert into test_bpchar_byte values (23, '23'::int2);
insert into test_bpchar_byte values (24, '24'::float4);
insert into test_bpchar_byte values (25, '25'::float8);
insert into test_bpchar_byte values (26, '26'::numeric);
select val from test_bpchar_byte;
drop table test_bpchar_byte;