\! gs_ktool -d all
\! gs_ktool -g

DROP CLIENT MASTER KEY IF EXISTS moneyCMK CASCADE;
CREATE CLIENT MASTER KEY moneyCMK WITH ( KEY_STORE = gs_ktool , KEY_PATH = "gs_ktool/1" , ALGORITHM = AES_256_CBC);
CREATE COLUMN ENCRYPTION KEY moneyCEK WITH VALUES (CLIENT_MASTER_KEY = moneyCMK, ALGORITHM = AEAD_AES_256_CBC_HMAC_SHA256);

create table IF NOT EXISTS money_type_enc(c1 int, 
c2 money ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = moneyCEK, ENCRYPTION_TYPE = DETERMINISTIC)
);

-- DROP TABLE money_type;
DROP TABLE  IF EXISTS money_type_enc;
DROP COLUMN ENCRYPTION KEY moneyCEK;
DROP CLIENT MASTER KEY moneyCMK;

\! gs_ktool -d all
