-- modify enble_segment parameter
drop table if exists tab_segment;
drop table if exists tab_segment_off;
drop table if exists tab_segment_on;
show enable_segment;
alter system set enable_segment = on;
select pg_sleep(1);
show enable_segment;
create table tab_segment(a int);
create table tab_segment_off(a int) with(segment=off);
create table tab_segment_on(a int) with(segment=on);
create table tab_segment_compress(a int) with(compresstype=2,compress_chunk_size=512,compress_level=1);
\d+ tab_segment;
\d+ tab_segment_off;
\d+ tab_segment_on;
drop table tab_segment;
drop table if exists tab_segment_off;
drop table if exists tab_segment_on;
drop table if exists tab_segment_compress;
select pg_sleep(1);
show enable_segment;
alter system set enable_segment = off;
select pg_sleep(1);
show enable_segment;
create table tab_segment(a int);
create table tab_segment_off(a int) with(segment=off);
create table tab_segment_on(a int) with(segment=on);
\d+ tab_segment;
\d+ tab_segment_off;
\d+ tab_segment_on;
drop table tab_segment;
drop table if exists tab_segment_off;
drop table if exists tab_segment_on;
