create table a(id1 int, id2 int);
create table b(id1 int, id2 int);
insert into a select n,n from generate_series(-5,5) n;
insert into b select n,n from generate_series(0,5) n;
explain(costs off) select count(*) from a inner join  b on a.id1 > b.id1 where (sqrt(a.id1) < 10 and b.id2 < 10) or (sqrt(a.id1) > 5 and b.id2 > 0);
select count(*) from a inner join  b on a.id1 > b.id1 where (sqrt(a.id1) < 10 and b.id2 < 10) or (sqrt(a.id1) > 5 and b.id2 > 0);
create table ta(id int,id1 int);
create table tb(id int,id1 int);
insert into ta values (1, 1);
insert into ta values (2, 2);
insert into ta values (3, 3);
insert into ta values (4, 4);
insert into tb values (1, 1);
insert into tb values (2, 2);
insert into tb values (3, 3);
insert into tb values (4, 4);
select * from ta,tb where (ta.id=1 and tb.id=2) or (ta.id=2 and tb.id=1);
explain(costs off) select * from ta,tb where (ta.id=1 and tb.id=2) or (ta.id=2 and tb.id=1);
set sql_beta_feature=extract_pushdown_or_clause;
explain(costs off) select count(*) from a inner join  b on a.id1 > b.id1 where (sqrt(a.id1) < 10 and b.id2 < 10) or (sqrt(a.id1) > 5 and b.id2 > 0);
select count(*) from a inner join  b on a.id1 > b.id1 where (sqrt(a.id1) < 10 and b.id2 < 10) or (sqrt(a.id1) > 5 and b.id2 > 0);
select * from ta,tb where (ta.id=1 and tb.id=2) or (ta.id=2 and tb.id=1);
explain(costs off) select * from ta,tb where (ta.id=1 and tb.id=2) or (ta.id=2 and tb.id=1);
drop table ta;
drop table tb;
drop table a;
drop table b;
set sql_beta_feature=none;

