DROP table if exists aes_cipher;
create table aes_cipher(cipher text, key varchar(16));
insert into aes_cipher values(gs_encrypt_sm4('hello','1234@abc'),'1234@abc');
insert into aes_cipher values(gs_encrypt_sm4('hello','1234@abc'),'1234@abc');
insert into aes_cipher select * from aes_cipher;
insert into aes_cipher select * from aes_cipher;
insert into aes_cipher select * from aes_cipher;
insert into aes_cipher values(gs_encrypt_sm4('hello','1@abcdef'),'1@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','2@abcdef'),'2@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','3@abcdef'),'3@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','4@abcdef'),'4@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','5@abcdef'),'5@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','6@abcdef'),'6@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','7@abcdef'),'7@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','8@abcdef'),'8@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','9@abcdef'),'9@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','10@abcdef'),'10@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','11@abcdef'),'11@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','12@abcdef'),'12@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','13@abcdef'),'13@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','14@abcdef'),'14@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','15@abcdef'),'15@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','16@abcdef'),'16@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','17@abcdef'),'17@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','18@abcdef'),'18@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','19@abcdef'),'19@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','20@abcdef'),'20@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','21@abcdef'),'21@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','22@abcdef'),'22@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','23@abcdef'),'23@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','24@abcdef'),'24@abcdef');
insert into aes_cipher values(gs_encrypt_sm4('hello','25@abcdef'),'25@abcdef');
select gs_decrypt_sm4(cipher,key) from aes_cipher order by 1;
DROP table aes_cipher;
--function test
select gs_encrypt_sm4('along','1234@abc');
select gs_decrypt_sm4(gs_encrypt_sm4('along','1234@abc'),'1234@abc');
--insert/select test
create table aes_table(name text);
insert into aes_table values(gs_encrypt_sm4('he@#llo','1234@abc'));		--special characters
select gs_decrypt_sm4(name,'1234@abc') from aes_table order by 1;
drop table aes_table;
--column type test
create table aes_type_bytea(name bytea);
create table aes_type_varchar(name varchar(100));
create table aes_type_nvarchar2(name nvarchar2(100));
create table aes_type_int(id int);
create table aes_type_numeric(id numeric);
insert into aes_type_bytea values(gs_encrypt_sm4('along','1234@abc'));
insert into aes_type_varchar values(gs_encrypt_sm4('along','1234@abc'));
insert into aes_type_nvarchar2 values(gs_encrypt_sm4('along','1234@abc'));
insert into aes_type_int values(gs_encrypt_sm4('along','1234@abc'));
insert into aes_type_numeric values(gs_encrypt_sm4('along','1234@abc'));
drop table aes_type_bytea;
drop table aes_type_varchar;
drop table aes_type_nvarchar2;
drop table aes_type_int;
drop table aes_type_numeric;
--data type test
create table aes_data_type(c1 int4, c2 int8, c3 numeric(18,2), c4 float8, c5 money, c6 boolean, c7 varchar(15), c8 text, c9 date, c10 bytea);
insert into aes_data_type values(123456,654321,123.21,654321.123456,100,TRUE,'varchar','text','2017-12-07', 'bytea');
create table aes_data_encrypt(e1 text, e2 text, e3 text, e4 text, e5 text, e6 text, e7 text, e8 text, e9 text, e10 text);
insert into aes_data_encrypt select gs_encrypt_sm4(c1,'1234@abc'), gs_encrypt_sm4(c2,'1234@abc'), gs_encrypt_sm4(c3,'1234@abc'),
gs_encrypt_sm4(c4,'1234@abc'), gs_encrypt_sm4(c7,'1234@abc'), gs_encrypt_sm4(c8,'1234@abc'), gs_encrypt_sm4(c9,'1234@abc') from aes_data_type;
select gs_encrypt_sm4(c5,'1234@abc') from aes_data_type;
select gs_encrypt_sm4(c6,'1234@abc') from aes_data_type;
select gs_encrypt_sm4(c10,'1234@abc') from aes_data_type;
drop table aes_data_type;
drop table aes_data_encrypt;
--boundary test
select gs_decrypt_sm4(gs_encrypt_sm4('','1234@abc'),'1234@abc');
select gs_decrypt_sm4(gs_encrypt_sm4('along','1234@abc'),null);
select gs_encrypt_sm4('along',null);
select gs_decrypt_sm4(gs_encrypt_sm4('comeon','1234567@abcdefgh'),'1234567@abcdefgh');
select gs_decrypt_sm4(gs_encrypt_sm4('aessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfalflsasssasdfaessdsllaessdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfassasdfaessdsllaessdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfdfaessasdfasdfasdfsdfadllaessdsllsdlflsasssasdfaessfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessllaessdsllsdlflsasssasdfaessfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessllsdlflsasssasdfaesssdlflssasdfassdllsdlflsasssasdfaesssdlflssasdfassdsdllsdlflsasssasdfaesssdlflssasdfassdaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlllsdlsdlaaabbllsdlsdlaaabbllsdlsdlaaabbdasdfsdfaasdfasdfsdfsdasdfadsadfasdfadsadfasssdlflssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssssssssdlflssassssdlflssasssasssssssdlflssasssasssassssdlflssasssasssssssdssdlfldlflsasssassssdlflssssdlflssasasssassssdlflssasssasssssssdlflssasssasssssssdlflssasssasssasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssssssssssdlfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfalflsasssasdfaessdsllaessdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfassasdfaessdsllaessdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfdsllsdlflsasssasdfaessasdfasdfasdfsdfadfdfadfdfaessasdfasdfasdfsdfadllaessdsllsdlflsasssasdfaessfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessllaessdsllsdlflsasssasdfaessfaessdsllsdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflsasssasdfsdlflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessllsdlflsasssasdfaesssdlflssasdfassdllsdlflsasssasdfaesssdlflssasdfassdsdllsdlflsasssasdfaesssdlflssasdfassdaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlflsasssasdfaessdsllaessdsllsdlflsasssasdfaesssdlflssasdfaessflsasasdfaessflsasssasdfaessllsdlflsasssasdfaesssdlflssasdfassdlflssasdfaessflsasssasdfaessdsllsdlllsdlsdlaaabbllsdlsdlaaabbllsdlsdlaaabbdasdfsdfaasdfasdfsdfsdasdfadsadfasdfadsadfasssdlflssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssdlflssasssassssdlflssaslssassssdlflssasssassssdlflssasssassssdlflssasssassssdlflssasasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssssssssdlflssassssdlflssasssasssssssdlflssasssasssassssdlflssasssasssssssdssdlfldlflsasssassssdlflssssdlflssasasssassssdlflssasssasssssssdlflssasssasssssssdlflssasssasssasssassssdlflssasssassssdlflssasasssassssdlflssasssasssssssdlflssasssassssssssssssdlf','1234@abc'),'1234@abc');
select gs_encrypt_sm4('along','1234');
select gs_decrypt_sm4(gs_encrypt_sm4('comeon','12345678@abcdefgh'),'12345678@abcdefgh');