DROP table if exists aes_cipher;
create table aes_cipher(cipher text, key varchar(16));
insert into aes_cipher values(gs_encrypt_aes128('hello','1234@abc'),'1234@abc');
insert into aes_cipher values(gs_encrypt_aes128('hello','1234@abc'),'1234@abc');
insert into aes_cipher select * from aes_cipher;
insert into aes_cipher select * from aes_cipher;
insert into aes_cipher select * from aes_cipher;
insert into aes_cipher values(gs_encrypt_aes128('hello','1@abcdef'),'1@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','2@abcdef'),'2@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','3@abcdef'),'3@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','4@abcdef'),'4@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','5@abcdef'),'5@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','6@abcdef'),'6@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','7@abcdef'),'7@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','8@abcdef'),'8@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','9@abcdef'),'9@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','10@abcdef'),'10@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','11@abcdef'),'11@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','12@abcdef'),'12@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','13@abcdef'),'13@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','14@abcdef'),'14@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','15@abcdef'),'15@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','16@abcdef'),'16@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','17@abcdef'),'17@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','18@abcdef'),'18@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','19@abcdef'),'19@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','20@abcdef'),'20@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','21@abcdef'),'21@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','22@abcdef'),'22@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','23@abcdef'),'23@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','24@abcdef'),'24@abcdef');
insert into aes_cipher values(gs_encrypt_aes128('hello','25@abcdef'),'25@abcdef');
select gs_decrypt_aes128(cipher,key) from aes_cipher order by 1;
DROP table aes_cipher;
