show current_schema;
select current_schema;
create schema temp;
set current_schema to temp;
show current_schema;
reset current_schema;
set current_schema to 111;
show current_schema;
show search_path;
reset search_path;
show search_path;
show current_schema;
show current_schema;
select current_schema;
create schema temp;
set current_schema to temp;
show current_schema;
reset current_schema;
set current_schema to 111;
show current_schema;
show search_path;
reset search_path;
show search_path;
show current_schema;
