CREATE TABLE TBL_CU_TEST_ITEMS (
    CU_ITEM_SK        INTEGER NOT NULL
  , CU_ITEM_ID        CHAR(16) NOT NULL
  , CU_REC_START_DATE DATE
  , CU_REC_END_DATE   DATE
  , CU_ITEM_DESC      VARCHAR(200)
  , CU_CURRENT_PRICE  DECIMAL(7,2)
  , CU_WHOLESALE_COST DECIMAL(7,2)
  , CU_BRAND_ID       INTEGER
  , CU_BRAND          CHAR(50)
  , CU_CLASS_ID       INTEGER
  , CU_CLASS          CHAR(50)
  , CU_CATEGORY_ID    INTEGER
  , CU_CATEGORY       CHAR(50)
  , CU_MANUFACT_ID    INTEGER
  , CU_MANUFACT       CHAR(50)
  , CU_SIZE           CHAR(20)
  , CU_FORMULATION    CHAR(20)
  , CU_COLOR          CHAR(20)
  , CU_UNITS          CHAR(10)
  , CU_CONTAINER      CHAR(10)
  , CU_MANAGER_ID     INTEGER
  , CU_PRODUCT_NAME   CHAR(50)
  ) WITH (ORIENTATION = COLUMN);  
  
INSERT INTO TBL_CU_TEST_ITEMS
SELECT
  V, 'CUID-' || V
, NOW(), NOW() + 10
, 'XXXXXXXXXXX' || SIN(V)
, SIN(V), COS(V)
, V, 'BRAND-' || V
, V % 103, 'CLASS-' || V
, V % 79, 'CATEGORY-' || V
, V % 47, 'MANUFACT-' || V
, 'SIZE-CU'
, 'FORMULATION', 'COLOR', 'UNITS', 'CCCCC'
, V % 91, 'PRODUCT' || V
FROM GENERATE_SERIES(1, 100000) AS V;

SELECT COUNT(*)
FROM TBL_CU_TEST_ITEMS
TABLESAMPLE HYBRID (100,100) REPEATABLE (10)
WHERE CU_ITEM_SK > 7000;


-- Test case for PARTITION table
CREATE TABLE RANGE_CU_TEST_ITEMS (
    CU_ITEM_SK        INTEGER NOT NULL
  , CU_ITEM_ID        CHAR(16) NOT NULL
  , CU_REC_START_DATE DATE
  , CU_REC_END_DATE   DATE
  , CU_ITEM_DESC      VARCHAR(200)
  , CU_CURRENT_PRICE  DECIMAL(7,2)
  , CU_WHOLESALE_COST DECIMAL(7,2)
  , CU_BRAND_ID       INTEGER
  , CU_BRAND          CHAR(50)
  , CU_CLASS_ID       INTEGER
  , CU_CLASS          CHAR(50)
  , CU_CATEGORY_ID    INTEGER
  , CU_CATEGORY       CHAR(50)
  , CU_MANUFACT_ID    INTEGER
  , CU_MANUFACT       CHAR(50)
  , CU_SIZE           CHAR(20)
  , CU_FORMULATION    CHAR(20)
  , CU_COLOR          CHAR(20)
  , CU_UNITS          CHAR(10)
  , CU_CONTAINER      CHAR(10)
  , CU_MANAGER_ID     INTEGER
  , CU_PRODUCT_NAME   CHAR(50)
  ) WITH (ORIENTATION = COLUMN)
PARTITION BY RANGE (CU_ITEM_SK) (
  PARTITION CU_ITEM_P1 VALUES LESS THAN(1000), 
  PARTITION CU_ITEM_P3 VALUES LESS THAN(3000), 
  PARTITION CU_ITEM_P5 VALUES LESS THAN(5000), 
  PARTITION CU_ITEM_P7 VALUES LESS THAN(7000), 
  PARTITION CU_ITEM_P9 VALUES LESS THAN(9000), 
  PARTITION CU_ITEM_MAX VALUES LESS THAN(MAXVALUE)
);

INSERT INTO RANGE_CU_TEST_ITEMS
SELECT
  V, 'CUID-' || V
, NOW(), NOW() + 10
, 'XXXXXXXXXXX' || SIN(V)
, SIN(V), COS(V)
, V, 'BRAND-' || V
, V % 103, 'CLASS-' || V
, V % 79, 'CATEGORY-' || V
, V % 47, 'MANUFACT-' || V
, 'SIZE-CU'
, 'FORMULATION', 'COLOR', 'UNITS', 'CCCCC'
, V % 91, 'PRODUCT' || V
FROM GENERATE_SERIES(1, 100000, 5) AS V;

SELECT COUNT(*)
FROM RANGE_CU_TEST_ITEMS
TABLESAMPLE HYBRID (100,100) REPEATABLE (10)
WHERE CU_ITEM_SK > 7000;

