-- TEST: copyfuncs.c
START TRANSACTION;
	DROP TABLE IF EXISTS TEST1_P;
	CREATE TABLE TEST1_P ( TEST1_F1 INT ) PARTITION BY RANGE(TEST1_F1) ( PARTITION TEST1_P1 VALUES LESS THAN (1000));
	CREATE INDEX INDEX_ON_TEST1_P ON TEST1_P(TEST1_F1) LOCAL (PARTITION INDEX_ON_TEST1_P1);
COMMIT;

START TRANSACTION;
	INSERT INTO TEST1_P select GENERATE_SERIES(0, 999, 1);
	SELECT COUNT(*) FROM TEST1_P where TEST1_F1 < 10;
COMMIT;

-- TEST: outfuncs.c
CREATE VIEW VIEW_TEST1_P AS SELECT * FROM TEST1_P;


-- TEST: readfuncs.c
SELECT PG_GET_VIEWDEF('VIEW_TEST1_P');
SET ENABLE_SEQSCAN = FALSE;
SET ENABLE_BITMAPSCAN = FALSE;
EXPLAIN (COSTS off) SELECT * FROM TEST1_P WHERE TEST1_F1 > 5000;
RESET ENABLE_SEQSCAN;
RESET ENABLE_BITMAPSCAN;

-- clean up
DROP TABLE TEST1_P CASCADE;