drop table if exists tb1_column cascade;
create table tb1_column(
col_tinyint tinyint not null default '3',
col_smallint smallint not null default '7',
col_integer integer,
col_int int,
col_binary_integer binary_integer,
col_bigint bigint,
col_numeric numeric,
col_numeric1 numeric(38),
col_numeric2 numeric(38,7),
col_decimal decimal,
col_decimal1 decimal(38),
col_decimal2 decimal(38,7),
col_number1 number,
col_number2 number(38),
col_number5 number(38,7),
col_real real,
col_float4 float4,
col_double_precision double precision,
col_float8 float8,
col_float float,
col_float1 float(38),
col_binary_double binary_double,
col_dec dec,
col_dec1 dec(38),
col_dec2 dec(38,7),
col_integer1 integer(38),
col_integer2 integer(38,7),
col_money money,
col_boolean boolean,
col_char char,
col_char1 char(200),
col_character character,
col_character1 character(200),
col_nchar nchar,
col_nchar1 nchar(200),
col_varchar varchar(200),
col_character_varying character varying(200),
col_varchar2 varchar2(200) default 'aaaabbbb',
col_narchar2 nvarchar2(200) not null default 'aaaabbbb',
col_clob clob,
col_text text,
col_char2 "char",
col_bytea bytea,
col_date date not null default '2018-01-07 08:08:08',
col_time time,
col_time1 time(6),
col_time2 time without time zone,
col_time3 time(6) without time zone,
col_time4 time with time zone,
col_time5 time(6) with time zone,
col_timestamp timestamp,
col_timestamp1 timestamp(6),
col_timestamp2 timestamp without time zone,
col_timestamp3 timestamp(6) without time zone,
col_timestamp4 timestamp with time zone,
col_timestamp5 timestamp(6) with time zone,
col_smalldatetime smalldatetime,
col_interval interval day (1) to second (6),
col_interval1 interval,
col_interval2 interval year,
col_interval3 interval second (6),
col_interval4 interval hour to second (6),
col_cidr cidr,
col_inet inet,
col_bitn bit(10),
col_bit_varying bit varying(10)
)  with (ORIENTATION=COLUMN) TABLESPACE tbs_user_default;


--全局索引
create index idx_tbl_column_global_01 on tb1_column(col_tinyint,col_smallint,col_numeric,col_decimal) tablespace tbs_user_default;
create index idx_tbl_column_global_03 on tb1_column(col_bigint,col_varchar,col_timestamp2) tablespace tbs_user_default;
--创建comment
comment on column tb1_column.col_tinyint IS 'I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!';