drop table if exists tb1_partition cascade;
create table tb1_partition(
col_tinyint tinyint not null default '3',
col_smallint smallint not null default '7',
col_integer integer,
col_int int,
col_binary_integer binary_integer primary key,
col_bigint bigint,
col_numeric numeric,
col_numeric1 numeric(38),
col_numeric2 numeric(38,7),
col_decimal decimal,
col_decimal1 decimal(38),
col_decimal2 decimal(38,7),
col_number1 number,
col_number2 number(38),
col_number5 number(38,7),
col_real real,
col_float4 float4,
col_double_precision double precision,
col_float8 float8,
col_float float,
col_float1 float(38),
col_binary_double binary_double,
col_dec dec,
col_dec1 dec(38),
col_dec2 dec(38,7),
col_integer1 integer(38),
col_integer2 integer(38,7),
col_money money,
col_boolean boolean,
col_char char,
col_char1 char(200),
col_character character,
col_character1 character(200),
col_nchar nchar,
col_nchar1 nchar(200),
col_varchar varchar(200),
col_character_varying character varying(200),
col_varchar2 varchar2(200) default 'aaaabbbb',
col_narchar2 nvarchar2(200) not null default 'aaaabbbb',
col_clob clob,
col_text text,
col_name1 name,
col_char2 "char",
col_blob blob,
col_raw raw,
col_bytea bytea,
col_date date not null default '2018-01-07 08:08:08',
col_time time,
col_time1 time(6),
col_time2 time without time zone,
col_time3 time(6) without time zone,
col_time4 time with time zone,
col_time5 time(6) with time zone,
col_timestamp timestamp,
col_timestamp1 timestamp(6),
col_timestamp2 timestamp without time zone,
col_timestamp3 timestamp(6) without time zone,
col_timestamp4 timestamp with time zone,
col_timestamp5 timestamp(6) with time zone,
col_smalldatetime smalldatetime,
col_interval interval day (1) to second (6),
col_interval1 interval,
col_interval2 interval year,
col_interval3 interval second (6),
col_interval4 interval hour to second (6),
col_cidr cidr,
col_inet inet,
col_macaddr macaddr,
col_bitn bit(10),
col_bit_varying bit varying(10)
)partition by range(col_BINARY_INTEGER)
(
  PARTITION P_0500_BEFORE VALUES LESS THAN (50),
  PARTITION P_1000 VALUES LESS THAN (100),
  PARTITION P_1500 VALUES LESS THAN (150),
  PARTITION P_2000 VALUES LESS THAN (200),
  PARTITION P_2000_AFTER VALUES LESS THAN (MAXVALUE)
);

--增加唯一约束
alter table tb1_partition add constraint tb1_partition_uk1 unique(col_int,col_bigint,col_BINARY_INTEGER);
--local索引必须带全部分区
create index idx_tbl_partition_local_01 on tb1_partition(col_BINARY_INTEGER,col_raw asc,col_boolean,col_interval1 asc) local (partition P_0500,partition P_1000,partition P_1500,partition P_2000,partition P_2000_AFTER) tablespace tbs_user_default;
create index idx_tbl_partition_local_02 on tb1_partition(col_BINARY_INTEGER,col_float,col_numeric,col_raw,col_varchar2,col_interval1,col_date) local (partition P_0500,partition P_1000,partition P_1500,partition P_2000,partition P_2000_AFTER) tablespace tbs_user_default;
--创建comment
comment on column tb1_partition.col_tinyint IS 'I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!I am ok!!';