DROP SCHEMA IF EXISTS indexonly_ustore_smp CASCADE;
CREATE SCHEMA indexonly_ustore_smp;
SET CURRENT_SCHEMA TO indexonly_ustore_smp;

DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a INT, b INT, c INT) WITH (STORAGE_TYPE = USTORE);
CREATE INDEX i_t1 on t1(b);

--forward scan
--without analyze
SET QUERY_DOP = 1002;
-- 1 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,100), GENERATE_SERIES(1,100), GENERATE_SERIES(1,100));
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

-- with analyze
SET QUERY_DOP = 1002;
-- 1 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

SET QUERY_DOP = 1002;
-- 2 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,200), GENERATE_SERIES(1,200), GENERATE_SERIES(1,200));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

SET QUERY_DOP = 1002;
-- 4 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

SET QUERY_DOP = 1003;
-- 4 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

SET QUERY_DOP = 1004;
-- 4 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

SET QUERY_DOP = 1064;
-- 4 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

-- insert after analyze
SET QUERY_DOP = 1002;
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

-- delete after analyze
SET QUERY_DOP = 1002;
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
DELETE FROM t1 WHERE b <= 200;
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

-- vacuum
SET QUERY_DOP = 1002;
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
DELETE FROM t1 WHERE b <= 200;
VACUUM FULL t1;
EXPLAIN (COSTS OFF) SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;

-- function
SET QUERY_DOP = 1002;
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
CREATE OR REPLACE FUNCTION select_one_table(out1 OUT bigint)
AS 'SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1'
LANGUAGE SQL;
SELECT select_one_table();

--pbe
PREPARE p1 as SELECT /*+indexonlyscan(t1 i_t1)*/ COUNT(*) FROM t1;
EXECUTE p1;


-- backward scan
--without analyze
SET QUERY_DOP = 1002;
-- 1 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,100), GENERATE_SERIES(1,100), GENERATE_SERIES(1,100));
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

-- with analyze
SET QUERY_DOP = 1002;
-- 1 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

SET QUERY_DOP = 1002;
-- 2 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,200), GENERATE_SERIES(1,200), GENERATE_SERIES(1,200));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

SET QUERY_DOP = 1002;
-- 4 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

SET QUERY_DOP = 1003;
-- 4 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

SET QUERY_DOP = 1004;
-- 4 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

SET QUERY_DOP = 1064;
-- 4 page
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

-- insert after analyze
SET QUERY_DOP = 1002;
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

-- delete after analyze
SET QUERY_DOP = 1002;
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
DELETE FROM t1 WHERE b <= 200;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

-- vacuum
SET QUERY_DOP = 1002;
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
DELETE FROM t1 WHERE b <= 200;
VACUUM FULL t1;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);

-- function
SET QUERY_DOP = 1002;
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
CREATE OR REPLACE FUNCTION select_one_table(out1 OUT bigint)
AS 'SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC)'
LANGUAGE SQL;
SELECT select_one_table();

--pbe
PREPARE p2 as SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
EXECUTE p2;

--partiton table
SET QUERY_DOP = 1002;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a INT, b INT, c INT) 
WITH (STORAGE_TYPE = USTORE)
partition by range (b)
(
partition p1 values less than(150),
partition p2 values less than(300),
partition p3 values less than(450),
partition p4 values less than (maxvalue)
);
CREATE INDEX i_t1 on t1(b) local;
-- (1) some partition tables are empty.
INSERT INTO t1 VALUES(GENERATE_SERIES(1,300), GENERATE_SERIES(1,300), GENERATE_SERIES(1,300));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b ASC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b ASC);
-- (2) all partition tables are not empty.
TRUNCATE t1;
INSERT INTO t1 VALUES(GENERATE_SERIES(1,600), GENERATE_SERIES(1,600), GENERATE_SERIES(1,600));
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b ASC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b ASC);
DROP INDEX i_t1;
CREATE INDEX i_t1 on t1(b) global;
ANALYZE t1;
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b DESC);
EXPLAIN (COSTS OFF) SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b ASC);
SELECT COUNT(*) FROM (SELECT /*+indexonlyscan(t1 i_t1)*/ b FROM t1 ORDER BY b ASC);

RESET QUERY_DOP;
DROP FUNCTION indexonly_ustore_smp.select_one_table();
DROP TABLE indexonly_ustore_smp.t1;
SET CURRENT_SCHEMA=PUBLIC;
DROP SCHEMA indexonly_ustore_smp CASCADE;